name: 'Docker Buildx'

description: 'Caching container image for CI/CD runs'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
      with:
        install: true

    - name: Build Docker image and store in cache
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: false
        load: true
        tags: rs/make
        cache-from: type=gha
        cache-to: type=gha,mode=max
