;; -*- org-confirm-babel-evaluate: nil -*-
#+title:  Notes on the book `Quantum Computation and Quantum Information`
#+author: Reinhard Stahn
#+latex_header: \newcommand{\CC}{\mathbb{C}}
#+latex_header: \newcommand{\CU}{\mathrm{CU}}
#+latex_header: \newcommand{\CX}{\mathrm{CX}}
#+latex_header: \newcommand{\CZ}{\mathrm{CZ}}
#+startup: inlineimages latexpreview show2levels

Notes on the "Quantum Computation Bible" [cite: @ChuangNielsen2011].

TODOs:
- [X] Write Exercise x.y instead of exercise x.y in headings.
- [ ] Remove the numbers from (at least some) headings in the HTML output.
- [ ] How to tell the HTML exporter to recognize the latex macros (e.g. for \CZ).
- [X] Remove toplevel Heading "quantum bible", Make Parts toplevel.
- [ ] move latex_header to separate file
- [X] Use ~qiskit.circuit.Parameter~ ([[https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.assign_parameters.html][link]]) to draw some of the circuits.
- [X] Use ~print~ less often in code blocks to not pollute ipython when using ~%run quantum-bible.py~.
- [ ] Should these "Inline" Appendices be commented (not for export)?
- [ ] Setup some nice CSS.
- [ ] Comment out "Search for circuits" - it might be distracting?

* Part I
So far nothing to see here ... .

* Part II
** ACTIVE Chapter 4
  :PROPERTIES:
  :header-args:python: :session *chapter-4* :tangle yes :comments link :results silent :exports both
  :END:
*** Setup
**** Setup Python Libraries
#+name: setup-chapter-4
#+begin_src python
  from functools import reduce
  from itertools import product
  from typing import Any

  import sympy as sp
  from sympy import cos, exp, I, Matrix, pi, sin, sqrt
  from sympy.physics.quantum import TensorProduct
  from sympy.combinatorics import Permutation as Perm

  import numpy as np
  import numpy.typing as npt

  from qiskit.circuit import QuantumCircuit, Parameter as Param
#+end_src

**** Pauli- and Rotation-Matrices
The Pauli matrices, and some related matrices:

#+name: paulis-and-friends
#+begin_src python
  # The Paulis:
  X = Matrix([[0, 1], [1, 0]])
  Y = Matrix([[0, -I], [I, 0]])
  Z = Matrix([[1, 0], [0, -1]])

  # Identity
  Id = Matrix([[1, 0], [0, 1]])
  # Hadamard Gate
  H = Matrix([[1, 1], [1, -1]]) / sqrt(2)
  # Phase Gate (sqrt(Z))
  S = Matrix([[1, 0], [0, I]])
  # pi/8 Gate
  T = Matrix([[1, 0], [0, exp(pi * I / 4)]])

  # Rotation Operators
  # - Rz: Phase Shift
  # - Rx: "Strange" Rotation
  # - Ry: Real Rotation
  theta = sp.symbols('theta')
  Rz = Matrix([[exp(-I*theta/2), 0], [0, exp(I*theta/2)]])
  Rx = Matrix([[cos(theta/2), -I*sin(theta/2)], [-I*sin(theta/2), cos(theta/2)]])
  Ry = Matrix([[cos(theta/2), -sin(theta/2)], [sin(theta/2), cos(theta/2)]])
#+end_src

The rotation operators correspond to a rotation of angle $\theta$ around the respective axis in the
*Bloch Sphere* (See Exercise 4.6).

#+caption: The Bloch Sphere
#+name: bloch-sphere.svg
#+attr_org: :width 400px
#+attr_html: :style width: 50%
[[./images/bloch-sphere.svg]]

**** SWAP - a two-qubit Gate
The =SWAP= Gate takes two qubits and exchanges their state. It is a permutation on the basis vectors:

#+name: swap-gate
#+begin_src python
  SWAP = Matrix([
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
  ])
#+end_src

**** Controlled Gates
For the definition of the controlled gates we introduce the projections $P_j$ corresponding to the
computational basis. Moreover we generalize the Tensor Product (Kronecker Product on Matrices) to
take more then two argumentes (sympy only allows two arguments, which is not convenient).

#+name: projection-operators
#+begin_src python
  # First define the projections onto the computational basis
  P0 = Matrix([[1, 0], [0, 0]])
  P1 = Matrix([[0, 0], [0, 1]])

  def tprod(A1, *As):
      """Generalize TensorProduct to one and more then two arguments."""
      P = A1
      for A in As:
          P = TensorProduct(P, A)
      return P
#+end_src

The most basic controlled gates are the controlled Pauli Gates on two qubits. The function ~make_CU~
generalizes this construction to arbitrary single-qubit gates on arbitrary many wires:

#+name: controlled-pauli-gates
#+begin_src python
  # controlled X (NOT), Y, and Z gates
  CX = tprod(P0, Id) + tprod(P1, X)
  CY = tprod(P0, Id) + tprod(P1, Y)
  CZ = tprod(P0, Id) + tprod(P1, Z)


  def make_CU(num_wires: int, control: int, target: int, U: Matrix) -> Matrix:
      """Returns a controlled U Gate. U must be single qubit gate. Wires are
      numbered 0 to num_wires - 1."""
      assert 0 <= control < num_wires, "control out of range"
      assert 0 <= target < num_wires, "target out of range"
      assert control != target, "target must differ from control"
      assert U.rows == U.cols == 2, "U must be single-qubit gate"

      t0 = [Id]*num_wires
      t1 = [Id]*num_wires

      t0[control] = P0
      t1[control] = P1
      t1[target] = U

      return tprod(*t0) + tprod(*t1)
#+end_src

There are a few straightforward ways to generalize the above defined simple controlled gates.

- One can allow for multiple controls ($C^nU$ gates). One instance is the /Toffoli Gate/ aka $CCX$
  aka $C^2X$.
- Normally, e.g. $C^3X$ is "activated" by the bit pattern =111=. One can generalize this to let a
  different bit pattern, like =101=, activate it.
- One can also allow for $U$ to be a multi-qubit gate (multiple targets). In general this requires
  to specify how to wire the targets into $U$ (in which order) but for some examples like the
  /Fredkin Gate/ (aka =CSWAP=) this is an irrelevant question since the =SWAP= gate is symmetric in
  its inputs.

#+name: other-controlled-gates
#+begin_src python
  # Toffoli Gate aka CCX
  Toff = tprod(P0, P0, Id) + tprod(P0, P1, Id) + tprod(P1, P0, Id) + tprod(P1, P1, X)

  # Fredkin Gate aka CSWAP
  Fred = tprod(P0, Id, Id) + tprod(P1, SWAP)
#+end_src

Since we need them sometimes, in the following we define a factory for controlled gates with multiple controls.

#+name: make-CnU-gates
#+begin_src python
  def make_CnU(num_wires: int, controls: list[int], target: int, U: Matrix) -> Matrix:
      """Generalization of make_CU to several controls."""
      assert all([0 <= c < num_wires for c in controls]), "controls out of range"
      assert 0 <= target < num_wires, "target out of range"
      assert all([c != target for c in controls]), "target must differ from controls"
      assert U.rows == U.cols == 2, "U must be single-qubit gate"

      P = [P0, P1]

      CnU = None
      ts = []
      for bitlist in product(*[[0, 1]]*len(controls)):
          t = [Id]*num_wires

          for i, bit in enumerate(bitlist):
              t[controls[i]] = P[bit]

          ts.append(t)
      ts[-1][target] = U

      tensors = [tprod(*t) for t in ts]
      CnU = None
      for tensor in tensors:
          CnU = tensor if CnU is None else CnU + tensor

      return CnU
#+end_src

Some very simple Unit Tests:

#+name: unit-tests-for-controlled-gates
#+begin_src python
  assert make_CU(2, 0, 1, X) == CX, "Expected CX Gate (1)"
  assert make_CU(3, 1, 2, X) == tprod(Id, CX), "Expected CX Gate (2)"

  assert make_CnU(3, [0, 1], 2, X) == Toff, "Expected Toffoli Gate (1)"
  assert make_CnU(4, [1, 2], 3, X) == tprod(Id, Toff), "Expected Toffoli Gate (2)"
#+end_src

**** The Search for Circuits
In the following we document some /very basic/ approaches to find circuits consisting of
(relatively) simple gates to construct more complex gates.

The simplest non-trivial test case is to find the construction of $C^2U$ by a circuit consisting
only of controlled $X$, $V$, and $V^\dagger$, where $V$ is unitary with $V^2=U$. That is, we want to
find the construction from Figure 4.8 by exhausive search.

Possible Approaches (checkbox means that it is tried out within this document):
- [X] via sympy directly on matrices
- [X] via numpy (on matrices)
- [ ] via sympy but replacing matrices by permutations (in the spirit of the solution to exercise 4.27).
- [ ] outside python to avoid slow loops

***** Approach 1: via Sympy - Don't do this!
Here I document the approach via Sympy. This is not really a feasable approach since Matrix
Multiplication in Sympy is *extremely* slow. Of course this is not entirely unexpected since sympy
is not meant to be used in a brute force environment.

In fact, finding the circuit of Figure 4.8 via brute force is out of reach for this approach. It
can't be done within "reasonable" time limits. Going through all combinations of *just two gates*
(just 25=5*5 cases for the five admissible gates) already takes one second. For three gates the
number raises to almost nine seconds. So several minutes are to be expected in case of five gates. I
count this as "unreasonable" since this is still a very small problem.

*Conclusion:* Do not use sympy to calculate lots of matrix products.

****** The search routine
Just for completeness here is the code:

#+name: search-for-circuits-approach-via-sympy
#+begin_src python
  def make_all_CU(num_wires: int, U: Matrix, name: str, pred=None) -> list[Any]:
      """Generate all CU gates, whose control/target wires satisfy an optional predicate."""
      if pred is None:
          pred = (lambda c, t: True)

      # All possible combinations of (control, target).
      all_cts = list(product(range(num_wires), range(num_wires)))
      all_cts = [(c, t) for (c, t) in all_cts if c != t and pred(c, t)]

      gates = []
      for c, t in all_cts:
          gate = make_CU(num_wires, c, t, U)
          gates.append(dict(  # The output is a list of dicts
              name=name,
              ct=(c, t),
              gate=gate,
          ))

      return gates


  def sp_search_circuits(n: int, admissible_gates: list[Matrix], Wanted_Gate: Matrix) -> str:
      """Find all circuits with n gates implementing Wanted_Gate."""
      solutions = []
      for gates in product(*([admissible_gates]*n)):
          gs = [g["gate"] for g in gates]
          prod = reduce((lambda x, y: x*y), gs)
          if sp.simplify(prod) == Wanted_Gate:  # wanted gate should already be simplified
              solutions.append(" * ".join([f"{g['name']}{g['ct']}" for g in gates]))
      return solutions
#+end_src

****** Testing the search routine
Here we try it out. You can use ipython magic function ~%time~ to measure how slow this approach is.

#+name: search-for-circuits-approach-via-sympy-tests
#+begin_src python
  V = Matrix([[1 - I, 1 + I], [1 + I, 1 - I]]) / 2
  assert sp.simplify(V*V) == X, "Exercise 28: V must be sqrt(X)."


  def make_pred_CX(num_wires):
      def pred_CX(c, t):
          return c < t and t < num_wires - 1
      return pred_CX


  def make_pred_CV(num_wires: int):
      def pred_CV(c, t):
          return c < t and t == num_wires - 1
      return pred_CV


  adm_CX = make_all_CU(3, X, "CX", make_pred_CX(3))
  adm_CV = make_all_CU(3, V, "CV", make_pred_CV(3))
  adm_CVh = make_all_CU(3, V.H, "CVh", make_pred_CV(3))

  admissible_gates = adm_CX + adm_CV + adm_CVh

  CX01 = make_CU(3, 0, 1, X)
  CX02 = make_CU(3, 0, 2, X)
  CV02 = make_CU(3, 0, 2, V)
  assert sp_search_circuits(1, admissible_gates, CX01) == ['CX(0, 1)'], "sp_search_circuits: CX01"
  assert sp_search_circuits(1, admissible_gates, CV02) == ['CV(0, 2)'], "sp_search_circuits: CV02"
  # We comment this out since it takes about a second:
  # result = sorted(['CX(0, 1) * CV(0, 2)', 'CV(0, 2) * CX(0, 1)'])
  # assert sorted(sp_search_circuits(2, admissible_gates, CX01 * CV02)) == result, "sp_search_circuits: CX01 * CV02"
#+end_src

***** Approach 2: via Numpy
*IMPORTANT:* Complex numbers in numpy are always implemented via floats. To avoid the typical
floating point arithmetic issues we assume that all numbers are either integrals or more generally
multiples of some ~2**(-n)~. In that case floating point arithmetic is exact (up to overflow).

****** Reimplement some basic auxiliary functions for numpy
First we have to reimplement some functions we already use at the sympy side:

#+name: numpy-make-controlled-gates
#+begin_src python
  def np_kron(A1: npt.ArrayLike, *As: list[npt.ArrayLike]) -> np.ndarray:
      """Generalize TensorProduct to one and more then two arguments."""
      P = A1
      for A in As:
          P = np.kron(P, A)
      return P


  def np_make_CU(num_wires: int, control: int, target: int, U: np.ndarray) -> np.ndarray:
      """Returns a controlled U Gate. U must be single qubit gate. Wires are
      numbered 0 to num_wires - 1."""
      assert 0 <= control < num_wires, "control out of range"
      assert 0 <= target < num_wires, "target out of range"
      assert control != target, "target must differ from control"
      assert U.shape == (2, 2), "U must be single-qubit gate"

      t0 = [np_Id]*num_wires
      t1 = [np_Id]*num_wires

      t0[control] = np_P0
      t1[control] = np_P1
      t1[target] = U

      return np_kron(*t0) + np_kron(*t1)


  def np_make_CnU(num_wires: int, controls: list[int], target: int, U: np.ndarray) -> np.ndarray:
      """Generalization of make_CU to several controls."""
      assert all([0 <= c < num_wires for c in controls]), "controls out of range"
      assert 0 <= target < num_wires, "target out of range"
      assert all([c != target for c in controls]), "target must differ from controls"
      assert U.shape == (2, 2), "U must be single-qubit gate"

      P = [np_P0, np_P1]

      CnU = None
      ts = []
      for bitlist in product(*[[0, 1]]*len(controls)):
          t = [np_Id]*num_wires

          for i, bit in enumerate(bitlist):
              t[controls[i]] = P[bit]

          ts.append(t)
      ts[-1][target] = U

      tensors = [np_kron(*t) for t in ts]
      CnU = None
      for tensor in tensors:
          CnU = tensor if CnU is None else CnU + tensor

      return CnU
#+end_src

****** Implementation of the search routine
Now we can implement the search routine:

#+begin_src python
  def np_make_all_CU(num_wires: int, U: Matrix, name: str, pred=None) -> list[Any]:
      if pred is None:
          pred = (lambda c, t: True)

      pairs = list(product(range(num_wires), range(num_wires)))
      pairs = [(c, t) for (c, t) in pairs if c != t and pred(c, t)]

      gates = []
      for c, t in pairs:
          gate = np_make_CU(num_wires, c, t, U)
          gates.append(dict(
              name=name,
              ct=(c, t),
              gate=gate,
          ))

      return gates


  def np_make_all_C2U(num_wires: int, U: np.ndarray, name: str, pred=None) -> list[Any]:
      if pred is None:
          pred = (lambda c, t: True)

      triples = list(product(*([range(num_wires)]*3)))
      triples = [(c0, c1, t) for (c0, c1, t) in triples if c0 < c1 and c0 != t and c1 != t and pred((c0, c1), t)]

      gates = []
      for c0, c1, t in triples:
          gate = np_make_CnU(num_wires, [c0, c1], t, U)
          gates.append(dict(
              name=name,
              ct=((c0, c1), t),
              gate=gate,
          ))

      return gates


  def np_search_circuit(n: int, admissible_gates: list[np.ndarray], Wanted_Gate: np.ndarray) -> str:
      """Find all solutions to exercise 4.28 with n gates."""
      solutions = []
      for gates in product(*([admissible_gates]*n)):
          gs = [g["gate"] for g in gates]
          prod = reduce((lambda x, y: x @ y), gs)
          if np.alltrue(prod == Wanted_Gate):
              solutions.append(" @ ".join([f"{g['name']}{g['ct']}" for g in gates]))
      return solutions


  def make_pred_CX(num_wires):
      def pred_CX(c, t):
          return c < t and t < num_wires - 1
      return pred_CX


  def make_pred_CV(num_wires: int):
      def pred_CV(c, t):
          return c < t and t == num_wires - 1
      return pred_CV


  def make_pred_CCX(num_wires: int):
      def pred_CCX(c, t):
          return c[0] < t and c[1] < t and t < num_wires - 1
      return pred_CCX
#+end_src

****** Pauli Matrices (and friends) for numpy
Now let us redefine the Pauli Matrices within numpy:

#+name: numpy-paul-matrices
#+begin_src python
  np_X = np.array([[0, 1], [1, 0]])
  np_Y = np.array([[0, -1j], [1j, 0]])
  np_Z = np.array([[1, 0], [0, -1]])

  np_Id = np.eye(2)
  np_P0 = np.array([[1, 0], [0, 0]])
  np_P1 = np.array([[0, 0], [0, 1]])

  # Half-integral-numbers should be OK too since floats are binary
  np_V = np.array([[1 - 1j, 1 + 1j], [1 + 1j, 1 - 1j]]) / 2
  np_Vt = np_V.conj().T
  assert np.alltrue(np_V @ np_V == np_X), "np_V must be sqrt(np_X)."
#+end_src

****** Basic Unit Tests
Very simple unit tests:

#+name: numpy-unit-tests-for-search-circuit
#+begin_src python
  np_adm_CX = np_make_all_CU(3, np_X, "CX", make_pred_CX(3))
  np_adm_CV = np_make_all_CU(3, np_V, "CV", make_pred_CV(3))
  np_adm_CVh = np_make_all_CU(3, np_Vt, "CVh", make_pred_CV(3))

  np_admissible_gates = np_adm_CX + np_adm_CV + np_adm_CVh

  # For convenience:
  def shorten_admissible_gates(admissible_gates):
      return [dict(name=ag["name"], ct=ag["ct"]) for ag in admissible_gates]


  np_CX01 = np_make_CU(3, 0, 1, np_X)
  np_CX02 = np_make_CU(3, 0, 2, np_X)
  np_CV02 = np_make_CU(3, 0, 2, np_V)
  np_CVt02 = np_make_CU(3, 0, 2, np_Vt)
  assert np_search_circuit(1, np_admissible_gates, np_CX01) == ['CX(0, 1)'], "np_search_circuit: CX01"
  assert sorted(np_search_circuit(1, np_admissible_gates, np_CV02)) == ['CV(0, 2)'], "np_search_circuit: CV02"
  result = sorted(['CX(0, 1) @ CV(0, 2)', 'CV(0, 2) @ CX(0, 1)'])
  assert sorted(np_search_circuit(2, np_admissible_gates, np_CX01 @ np_CV02)) == result, "np_search_circuit: CX01 @ CV02"
#+end_src

****** Find all minimal implementations of the Toffoli Gate
Finally we can actually search for all realizations of the Toffoli Gate (=CCX=):

#+name: numpy-search-toffoli
#+begin_src python
  np_Toff = np.array(Toff)

  # we deactivate the code since it takes around 10 seconds to execute
  if False:
      np_search_circuit(5, np_admissible_gates, np_Toff)
  # Produces among 19 others the solution from the book:
  # 'CV(0, 2) @ CX(0, 1) @ CVt(1, 2) @ CX(0, 1) @ CV(1, 2)',
#+end_src

We obtain 20 solutions using exactly 5 gates to represent the Toffoli (with less gates it is not possible):

#+begin_example
CX(0, 1) @ CV(0, 2) @ CVh(1, 2) @ CX(0, 1) @ CV(1, 2)
CX(0, 1) @ CV(1, 2) @ CX(0, 1) @ CVh(0, 2) @ CVh(1, 2)
CX(0, 1) @ CV(1, 2) @ CX(0, 1) @ CVh(1, 2) @ CVh(0, 2)
CX(0, 1) @ CV(1, 2) @ CVh(0, 2) @ CX(0, 1) @ CVh(1, 2)
CX(0, 1) @ CVh(0, 2) @ CV(1, 2) @ CX(0, 1) @ CVh(1, 2)
CX(0, 1) @ CVh(1, 2) @ CX(0, 1) @ CV(0, 2) @ CV(1, 2)
CX(0, 1) @ CVh(1, 2) @ CX(0, 1) @ CV(1, 2) @ CV(0, 2)
CX(0, 1) @ CVh(1, 2) @ CV(0, 2) @ CX(0, 1) @ CV(1, 2)
CV(0, 2) @ CX(0, 1) @ CVh(1, 2) @ CX(0, 1) @ CV(1, 2)
CV(0, 2) @ CV(1, 2) @ CX(0, 1) @ CVh(1, 2) @ CX(0, 1)
CV(1, 2) @ CX(0, 1) @ CV(0, 2) @ CVh(1, 2) @ CX(0, 1)
CV(1, 2) @ CX(0, 1) @ CVh(1, 2) @ CX(0, 1) @ CV(0, 2)
CV(1, 2) @ CX(0, 1) @ CVh(1, 2) @ CV(0, 2) @ CX(0, 1)
CV(1, 2) @ CV(0, 2) @ CX(0, 1) @ CVh(1, 2) @ CX(0, 1)
CVh(0, 2) @ CX(0, 1) @ CV(1, 2) @ CX(0, 1) @ CVh(1, 2)
CVh(0, 2) @ CVh(1, 2) @ CX(0, 1) @ CV(1, 2) @ CX(0, 1)
CVh(1, 2) @ CX(0, 1) @ CV(1, 2) @ CX(0, 1) @ CVh(0, 2)
CVh(1, 2) @ CX(0, 1) @ CV(1, 2) @ CVh(0, 2) @ CX(0, 1)
CVh(1, 2) @ CX(0, 1) @ CVh(0, 2) @ CV(1, 2) @ CX(0, 1)
CVh(1, 2) @ CVh(0, 2) @ CX(0, 1) @ CV(1, 2) @ CX(0, 1)
#+end_example

*** Exercises
**** Exercise 4.1
In Exercise 2.11, which you should do now if you haven’t already done it, you computed the
eigenvectors of the Pauli matrices. Find the points on the Bloch sphere which correspond to the
normalized eigenvectors of the different Pauli matrices.

Eigenvalues are +1 and -1 for all Paulis.

Eigenvectors (non-normalized, tip: ~Y.eigenvects()~):

| Pauli | EV +1    | EV -1    |
|-------+----------+----------|
| Z     | (1, 0)   | (0, 1)   |
| X     | (1, 1)   | (1, -1)  |
| Y     | (1j, -1) | (-1, 1j) |
**** Exercise 4.2
Let $x$ be a real number and $A$ a matrix such that $A^2 = I$. Show that

\begin{align*}
% \label{eq:exercise-4.2-1}
\exp(ixA) = \cos(x)I + i\sin(x)A
\end{align*}

Use this result to verify Equations (4.4) through (4.6).

*Solution:* The equation is obvious from polynomial series of ~exp, sin, cos~.

**** Exercise 4.3
Show that, up to a global phase, the π/8 gate satisfies $T = R_z(\pi/4)$.

*Solution:* It is easy to see that $T = \exp(i\pi/8) \cdot R_z(\pi/4)$. Demonstration:

#+name: exercise-4.3-1
#+begin_src python :results replace
  rz = Rz.subs(theta, pi/4)
  exp(1j*pi/8) * rz - T  # should be zero
#+end_src

#+RESULTS: exercise-4.3-1
: Matrix([[0, 0], [0, -exp(I*pi/4) + exp(0.25*I*pi)]])

**** Exercise 4.4
Express the Hadamard gate H as a product of Rx and Rz rotations and e^{iφ} for some φ.

*Solution:* Clearly a mere product of two factors can't produce the Hadamard gate. Hence we try to
find $\alpha,\beta,\gamma$ such that $R_z(\alpha)\cdot R_x(\gamma) \cdot R_z(\beta)$ is the Hadamard
up to the phase factor. Due to the sqrt of 2 factor appearing in $H$ we deduce that $\gamma=\pm\pi/2$
is a good bet. Knowing what comes we choose $\gamma=\pi/2$.

#+name: exercise-4.4-1
#+begin_src python :results value latex replace
  a, b = sp.symbols('\\alpha \\beta')

  ra = Rz.subs(theta, a)
  rb = Rz.subs(theta, b)
  rx = Rx.subs(theta, pi/2)

  h0 = ra * rx * rb
  simp = sp.simplify(sqrt(2)*h0)
  latex_formula = sp.latex(simp)

  #sp.preview(simp, viewer='file', filename='output.png', euler=False,
  #           dvioptions=['-D', '200', '-T', 'tight', '-bg', 'Transparent', '-fg', 'rgb 0.2 0.6 1.0'])
  #"output.png"

  latex_formula
#+end_src

A short calculation leads to:

#+RESULTS: exercise-4.4-1
#+begin_export latex
\left[\begin{matrix}e^{\frac{i \left(- \alpha - \beta\right)}{2}} & - i e^{- \frac{i \left(\alpha - \beta\right)}{2}}\\- i e^{\frac{i \left(\alpha - \beta\right)}{2}} & e^{\frac{i \left(\alpha + \beta\right)}{2}}\end{matrix}\right]
#+end_export

# RHS is result above
$$
R_z(\alpha)\cdot R_x(\pi/2) \cdot R_z(\beta) = \frac{1}{\sqrt{2}} \cdot
\left[\begin{matrix}e^{0.5 i \left(- \alpha - \beta\right)} & - 1.0 i e^{- 0.5 i \left(\alpha - \beta\right)}\\- 1.0 i e^{0.5 i \left(\alpha - \beta\right)} & e^{0.5 i \left(\alpha + \beta\right)}\end{matrix}\right]
$$

Hence setting $\alpha = \beta = \pi/2$ and $\phi = \pi/2$ we get

$$
H = e^{i\pi/2} \cdot R_z(\pi/2)\cdot R_x(\pi/2) \cdot R_z(\pi/2)
$$

**** Exercise 4.5
Prove that $(\hat{n}\cdot\sigma)^2 = I$, and use this to verify Equation (4.8).

*Solution:* This is easy to see from the following calculation:

#+name: exercise-4.5-1
#+begin_src python :results replace :exports both
  nx, ny, nz = sp.symbols('n_x n_y n_z')
  r = nx*X + ny*Y + nz*Z

  sp.simplify(r*r)
#+end_src

#+RESULTS: exercise-4.5-1
: Matrix([[n_x**2 + n_y**2 + n_z**2, 0], [0, n_x**2 + n_y**2 + n_z**2]])

By assumption we have ~nx**2 + ny**2 + nz**2 = 1~, hence follows the claim.

**** Exercise 4.6
Show that the rotation operators $R_{\hat{n}}(\theta)$ corresponds to a rotation of angle $\theta$
around the axis given by $\hat{n}$.

In other words: If we identify Qubits which just differ by phase, and identify each Qubit with its
(unique) Bloch vector, then the action of the quantum rotation is isomorphic to the ordinary
rotation with said axis and angle within the Bloch Sphere.
***** Proof
We divide the proof into several steps.

Let $|\psi\rangle = \cos\left(\theta /2\right) |0 \rangle \, + \, e^{i\varphi} \sin\left(\theta
/2\right) |1\rangle$ and recall the parameterization $p = (\sin\theta \cos\varphi,\;
\sin\theta \sin\varphi,\; \cos\theta)$
of the sphere.

****** (A) The claim is true for the special case $\hat{n} = (0, 0, 1)$.

PROOF: The standard basis $(|0\rangle, |1\rangle)$ diagonalizes $Z$. Hence, $Z$ trivially acts on
$\varphi$ which corresponds to a rotation around the z-axis. QED.

****** (B) The claim is true for the special case $\hat{n} = (0, 1, 0)$.

PROOF: It is sufficient to prove this for infinitesimal small angles. More precisely, we consider
$\delta \to 0$ and use $\approx$ for equality up to $O(\delta^2)$.

Let $r_y(\delta)$ be the rotation of angle $\delta$ around y-axis. Let $\theta' = \theta + a\delta$ and $\varphi'=\varphi+b\delta$
be the coordinates of $r_y(\delta)p$. We want to calculate $a, b$. We have:

\begin{align*}
r_y(\delta)p &\approx (\sin(\theta)\cos(\varphi) + \delta\cos(\theta),\;
  a \sin(\theta)\sin(\varphi),\;
  a \cos(\theta) - \delta\sin(\theta)\cos(\varphi)) \\
  &\approx (\sin\theta' \cos\varphi',\; \sin\theta' \sin\varphi',\; \cos\theta')
\end{align*}

It is advisable to first calculate $a$ from the third components and then $b$ from the second:

$$
  a = \cos(\varphi),\quad b = - \frac{\cos(\theta)\sin(\varphi)}{\sin(\theta)}
$$

Next we abbreviate $c=\cos(\theta/2)$, $s=\sin(\theta/2)$ and similarly $c', s'$ with $\theta'$ in place of $\theta$.

$$
  R_y(\delta) |\psi\rangle \approx (c - \frac{\delta}{2} e^{i\varphi} s) |0\rangle + (\frac{\delta}{2} c + e^{i\varphi}s) |1\rangle
$$

It is to be shown that this equals (up to $O(\delta^2)$)

$$
  e^{i\delta f} (c'|0\rangle + e^{i\varphi'}s'|1\rangle)
$$

for some real $x$. A calculation yields that this is indeed true for $f=-s\sin(\varphi)/2c$. QED.

****** (C) The claim is true for the special case $\hat{n} = (1, 0, 0)$.

PROOF: Observe that:

$$
  R_x(\theta) = R_y(\pi/2) R_z(\theta) R_y(-\pi/2)
$$

Moreover, recall that a similar formula holds for the rotations within the Bloch Sphere:

$$
  r_x(\theta) = r_y(\pi/2) r_z(\theta) r_y(-\pi/2)
$$

This together with (A) and (B) implies the claim. QED.

****** Intermezzo
Let $\hat{n} = (x, y, z)$, and $a = x + iy$. Then

$$
  N := \hat{n}\cdot(X, Y, Z) = \left(\begin{matrix} z & \overline{a} \\ a & -z \end{matrix}\right)
$$

It remains to show the claim for $N$.

****** (D) There exist $\alpha,\beta$ such that:

$$
  R_{\hat{n}}(\theta) = R_x(\alpha) R_y(\beta) \cdot R_z(\theta) \cdot R_y(-\beta) R_x(-\alpha)
$$

PROOF: The expression on the right simplifies to

\begin{bmatrix}
  \cos(\alpha)\cos(\beta) & \sin(\beta) + i \sin(\alpha)\cos(\beta) \\
  \sin(\beta) - i \sin(\alpha)\cos(\beta) & -\cos(\alpha)\cos(\beta)
\end{bmatrix}

It is not hard to see that $\alpha,\beta$ can be chosen such that this equals $N$. The concrete
values would be needed to determine the axis of rotation. However, we determine it another way. QED.

****** (E) $R_{\hat{n}}(\alpha)$ corresponds to a rotation of angle $\alpha$ around /some/ axis
(which is independent of the angle).

PROOF: This is a direct consequence of (D), together with (B) and (C). QED.

****** (F) The angle in (E) is indeed $\hat{n}$.

PROOF: We have to show that the positive eigenvector $v_+$ of $R_{\hat{n}(\alpha)}$ corresponds to
$\hat{n}$ on the Bloch sphere. Therefore let us calculate the eigenvalues:

#+name: exercise-4.6
#+begin_src python :results replace
  x, y, z = sp.symbols('x y z')
  N = Matrix([[z, x - I*y], [x + I*y, -z]])
  ev = N.eigenvects()

  # Keep in mind that x^2 + y^2 + z^2 = 1
  output=""
  for i in [0, 1]:
      output += f"eigenvalue = {ev[i][0]}\neigenvector = {ev[i][2]}"
      if i==0: output += "\n\n"
  output
#+end_src

#+RESULTS: exercise-4.6
: eigenvalue = -sqrt(x**2 + y**2 + z**2)
: eigenvector = [Matrix([
: [z/(x + I*y) - sqrt(x**2 + y**2 + z**2)/(x + I*y)],
: [                                               1]])]
:
: eigenvalue = sqrt(x**2 + y**2 + z**2)
: eigenvector = [Matrix([
: [z/(x + I*y) + sqrt(x**2 + y**2 + z**2)/(x + I*y)],
: [                                               1]])]

We see that the normalized eigenvectors for $\pm 1$ are:

$$
  v_{\pm} = \frac{1}{\sqrt{2}} \left(
    \pm \sqrt{1 \pm z}\cdot|0\rangle + \frac{x + iy}{\sqrt{1 \pm z}} \cdot |1\rangle \right)
$$

Let $\theta,\varphi$ such that

$$
  \hat{n} =: (\sin\theta \cos\varphi,\; \sin\theta \sin\varphi,\; \cos\theta)
$$

Let us abbreviate $c=\cos(\theta/2)$, $s=\sin(\theta/2)$. By the usual trigonometric identities we have:

$$
  \hat{n} = (2sc\cos(\varphi), 2sc\sin(\varphi), c^2 - s^2)
$$

Plugging this into the above formula for $v_+$ we see that indeed

$$ |\psi\rangle = c |0\rangle + e^{i\varphi}s |1\rangle $$

which proofs the claim. QED.

****** Conclusion
(F) proves the claim QED[exercise 4.6].

**** Exercise 4.7
Show that $XYX = - Y$ and use this to prove that $X R_y(\theta)X = R_y(-\theta)$.

*Solution:* Follows from $(XY)X = iZX = i^2Y$ (see [[id:8fd70970-1282-4a24-ab47-5eecf832498f][Pauli Matrices]]).
**** Exercise 4.8
An arbitrary single qubit unitary operator can be written in the form

$$ U = \exp(i\alpha) R_{\hat{n}} (\theta) $$

for some real numbers $\alpha$ and $\theta$, and a real three-dimensional unit vector $\hat{n}$.

1. Prove this fact.
2. Find values for the Hadamard gate $H$.
3. Find values for the phase gate $S = \sqrt{Z}$.

***** Proof of 1
:PROPERTIES:
:CUSTOM_ID: exercise-4-8-part-1
:END:
PROOF: Clearly every unitary Matrix has the form:

$$
  U = e^{i\gamma} \begin{pmatrix} e & -\overline{f} \\ f & \overline{e} \end{pmatrix}
  \text{ where } |e|^2 + |f|^2 = 1,
$$

since the columns have to be orthogonal. In the following we show that the rotation operators are
*characterized* as those unitary operators which look like the RHS without the phase factor.

We have:

$$
R_{\hat{n}}(\theta) = e^{-i\theta N/2} = \left(\begin{matrix}
  \cos(\theta/2) - iz \sin(\theta/2) & -i\overline{a} \sin(\theta/2) \\
  -ia \sin(\theta/2) & \cos(\theta/2) + iz \sin(\theta/2) \end{matrix}\right)
$$

where $\hat{n} = (x, y, z)$ and $a = x + iy$. It is sufficient to show that the First column of the
rotation opterator can be made equal to $(e, f)$, since the second column of $U$ is fixed
by unitarity - up to a phase factor (this is where the $\alpha$ kicks in).

Abbreviating $\zeta = \cos(\theta/2) - iz \sin(\theta/2)$ and decomposing $a = e^{i\varphi}|a|$ we
see that the first columnt of the rotation is:

$$ (\zeta, -i e^{i \varphi} \sqrt{1 - |\zeta|^2}) $$

Clearly $\zeta$ can be chosen to be any complex number with modulus at most $1$. Once this is fixed,
the second component can be made any number with modulus $\sqrt{1-|\zeta|^2}$. Hence the system

\begin{align*}
  \alpha &= \gamma \\
  \zeta &= e \\
  -i e^{i\varphi} &= f/|f| \text{ if } f \neq 0
\end{align*}

has a (unique) solution, which proves the claim. QED.

***** Part 2
We follow the proof of Part 1 and first represent $H$ in this special form:

$$
  H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}
    = \frac{i}{\sqrt{2}} \begin{pmatrix} -i & -i \\ -i & i \end{pmatrix}
$$

Hence $\zeta=-i/\sqrt{2}$ and $e^{i\varphi}=1$. This in turn leads to $x=z=1/\sqrt{2}$, $z=0$ and
$\theta=\pi$. In other words:

$$
  H = i R_{(\hat{x}+\hat{z})/\sqrt{2}}(\pi) = \frac{1}{\sqrt{2}} \left( X + Z \right).
$$

***** Part 3
Recall $Z = i R_z(\pi)$, hence:

$$ S = e^{i\pi/4} R_z(\pi/2). $$

**** Exercise 4.9
Explain why any single qubit unitary operator may be written in the form (4.12).

*Solution:* This essentially follows from the first lines of the proof of part 1 in [[#exercise-4-8-part-1][exercise 4.8]]
(representation of $U$).

**** Exercise 4.10
Give a decomposition analogous to Theorem 4.1 but using $R_x$ instead of $R_z$.

***** Solution
By Theorem 4.1 we find the following representation of $HUH$:

$$
  HUH = e^{i\alpha} R_z(\beta)\cdot R_y(\gamma)\cdot R_z(\delta)
$$

Conjugating this again with $H$ we get:

$$
  U = e^{i\alpha} R_x(\beta)\cdot R_y(-\gamma)\cdot R_x(\delta)
$$

QED.

**** Exercise 4.11
Suppose $\hat{m}$ and $\hat{n}$ are non-parallel real unit vectors in three dimensions. Use Theorem 4.1 to show that
an arbitrary single qubit unitary $U$ may be written

$$
  U = e^{i\alpha} R_{\hat{n}}(\beta) R_{\hat{m}}(\gamma) R_{\hat{n}}(\delta)
$$

for appropriate choices of α, β, γ and δ.

# No idea how to prove it directly from Theorem 4.1.

***** Proof
Since we consider only products of Gates we may identify Gates resp. Qubits which are equivalent up
to a phase factor. That is we work on the quotient space $\CC^2/\CC$ for the Qubits and
$\CC^{2\times2}/\CC$ for the Gates.

We have to proof that:

$$
  U \equiv R_{\hat{n}}(\beta) R_{\hat{m}}(\gamma) R_{\hat{n}}(\delta)
$$

In exercise 4.8 we proved that $U\equiv R_{\hat{k}}(\varepsilon)$ for some axis and angle. Let us
denote by $r$ the (ordinary) rotations in the Bloch Sphere. By exercise 4.6 we know that the quantum
roations are isomorphic to the corresponding ordinary rotations. That is, we have to show:

$$
  r_{\hat{k}}(\varepsilon) = r_{\hat{n}}(\beta) r_{\hat{m}}(\gamma) r_{\hat{n}}(\delta) .
$$

On the other hand this is a well known fact about the group of rotations (real orthogonal matrices
with determinant equal to 1) in three dimensions. We prove it here anyway:

The above equation is equivalent to

$$
   r_{\hat{n}}(-\beta) = r_{\hat{m}}(\gamma) r_{\hat{n}}(\delta) r_{\hat{k}}(-\varepsilon) .
$$

Since $\beta$ is a free parameter it suffices to show that the RHS maps $\hat{n}$ to itself, for
appropriate choices of $\gamma$ and $\delta$. Therefore let $\hat{t} = r_{\hat{k}}(-\varepsilon)\hat{n}$ and consider:

$$
  \hat{n} = r_{\hat{m}}(\gamma) r_{\hat{n}}(\delta) \hat{t} .
$$

Consider the Meridian $M_1$ around $\hat{n}$ which contains $\hat{t}$ and the Meridian $M_2$ around
$\hat{m}$ which contains $\hat{n}$. Since the two axes are not parallel the two Meridians have two
intersection points $a$ and $b$ (they can be equal in the trivial case $\hat{t}=\hat{n}$). Clearly
we can choose $\delta$ in such a way that $\hat{t}$ moves to one of the intersection points, say
$a$. Now, by definition of $M_2$ we can choose $\gamma$ in sich a way that $a$ moves to $\hat{n}$. QED.

**** Exercise 4.12
Give A, B, C, and α (in Corollary 4.2) for the Hadamard gate.

***** Solution
First let us find the parameters in

$$
  H = e^{i\alpha} R_z(\beta) R_y(\gamma) R_z(\delta)
$$

The RHS is given explicitly in (4.12) from where it is immediat that $\gamma=\pi/2$. The other three
parameters satisfy a linear system of equations, which can be solved easily: $\alpha=\pi/2$,
$\beta=0$, and $\delta=\pi$.

Hence:

\begin{align*}
  A &= R_z(\beta) R_y(\gamma/2) = R_y(\pi/4) = \frac{1}{2}
    \begin{pmatrix}
      \sqrt{\sqrt{2} + 2} & - \sqrt{2 - \sqrt{2}} \\
      \sqrt{2 - \sqrt{2}} & \sqrt{\sqrt{2} + 2}
    \end{pmatrix} \\
  B &= R_y(-\gamma/2) R_z(-(\delta + \beta)/2) = R_y(-\pi/4) R_z(-\pi/2) = \frac{1}{2}
    \begin{pmatrix}
      e^{\frac{i\pi}{4}} \sqrt{\sqrt{2} + 2} & e^{-\frac{i\pi}{4}} \sqrt{2 - \sqrt{2}} \\
      - e^{\frac{i\pi}{4}} \sqrt{2 - \sqrt{2}} & e^{-\frac{i\pi}{4}} \sqrt{\sqrt{2} + 2}
    \end{pmatrix} \\
  C &= R_z((\delta - \beta)/2) = R_z(\pi/2) =
    \begin{pmatrix}
      e^{- \frac{i \pi}{4}} & 0 \\
      0 & e^{\frac{i \pi}{4}}
    \end{pmatrix}
\end{align*}
**** Exercise 4.13
It is useful to be able to simplify circuits by inspection, using well-known identities. Prove the
following three identities:

$$ X = HZH,\quad Z = HXH,\quad Y = - HYH $$

***** Proof
The first two identities follow from the fact that $H$ is (unitary and) self-adjoint and contains
eigenvectors of $X$ as columns (and rows). The third identity follows from

$$ H = \frac{1}{\sqrt{2}} \left( X + Z \right). $$

and the commutator properties of the Paulis, e.g. $XY=iZ$ and its cyclic variations. Of course the
first two identities could also be proved like that.
**** Exercise 4.14
Use the previous exercise to show that $HTH=R_x(\pi/4)$, up to a global phase.

***** Proof
This follows from $T\equiv R_z(\pi/4)$ (up to phase factor) and $HZH=X$.
**** Exercise 4.15
The Bloch representation gives a nice way to visualize the effect of composing two rotations.

1. Prove that if a rotation through an angle β1 about the axis n̂1 is followed by a
rotation through an angle β2 about an axis n̂2 , then the overall rotation is through an angle β12
about an axis n̂12 given by

\begin{align*}
  c_{12} &= c_1 c_2 - s_1 s_2 \; \hat{n}_1 \cdot \hat{n}_2 \\
  s_{12} \hat{n}_{12} &= s_1 c_2 \; \hat{n}_1 + c_1 s_2 \; \hat{n}_2 + s_1 s_2 \; \hat{n}_2 \times \hat{n}_1 ,
\end{align*}

where $c_i=\cos(\beta_i/2)$, $s_i=\sin(\beta_i/2)$, $c_{12}=\cos(\beta_{12}/2)$, and $s_{12}=\sin(\beta_{12}/2)$.

2. Show that if β1 = β2 and n̂1 = ẑ these equations simplify to

\begin{align*}
  c_{12} &= c_2 − s_2 \; \hat{z} \cdot \hat{n}_2 \\
  s_{12} \hat{n}_12 &= sc \; (\hat{z} + \hat{n}_2) + s_2 \; \hat{n}_2 \times \hat{z} ,
\end{align*}

where $c=c_1$ and $s=s_1$.

*Remark:* /It seems/ (if we did no mistake) that there is a typo in the original formula for
$s_{12}\hat{n}_{12}$. We corrected this (hopefully).

***** Proof
We only proof the first assertion since the second one follows trivially from the first.

We use the previously established fact that the 3D-rotations are isomorphic to the Pauli rotation
operators (exercise 4.6). Along that way we essentially establish the relation between Quaternions
and 3D rotations (and Pauli rotations).

For a vector $\hat{n}$ let us define $N_{\hat{n}}=-i(n_1X+n_2Y+n_3Z)$. The composition of the two
rotations is given by:

$$
  (c_{12} + s_{12} N_{\hat{n}_{12}}) = (c_2 + s_2 N_{\hat{n}_2}) \cdot (c_1 + s_1 N_{\hat{n}_1}) .
$$

To spare us from the tedious work to expand the RHS by hand we use sympy for that. We are only
interested in algebraic operations and in particular we don't want to see any cumbersome matrix
expression. To help sympy we use the fact that the Quaterions can be modelled by the Pauli
Matrices. Just use the Identity matrix as the unit (the real number 1) and $-iX$, $-iY$, $-iZ$ as
the three imaginary units. Keep in mind that we only use the Quaterions as a trick to tell sympy
that we are not interested in Matrices. Essentially we still use the Pauli Rotations to prove the
claim.

#+name: exercise-4.15
#+begin_src python :results replace
  from sympy import Quaternion

  x1, y1, z1 = sp.symbols('x1 y1 z1')
  x2, y2, z2 = sp.symbols('x2 y2 z2')
  c1, c2, s1, s2 = sp.symbols('c1 c2 s1 s2')

  N1 = Quaternion(0, x1, y1, z1)
  N2 = Quaternion(0, x2, y2, z2)

  R1 = c1 + s1*N1
  R2 = c2 + s2*N2

  R2 * R1
#+end_src

#+RESULTS: exercise-4.15
: (c1*c2 - s1*s2*x1*x2 - s1*s2*y1*y2 - s1*s2*z1*z2) + (c1*s2*x2 + c2*s1*x1 - s1*s2*y1*z2 + s1*s2*y2*z1)*i + (c1*s2*y2 + c2*s1*y1 + s1*s2*x1*z2 - s1*s2*x2*z1)*j + (c1*s2*z2 + c2*s1*z1 - s1*s2*x1*y2 + s1*s2*x2*y1)*k

Rearranging the result for better readability:

#+begin_example
(c1*c2 - s1*s2*x1*x2 - s1*s2*y1*y2 - s1*s2*z1*z2)
+ (c1*s2*x2 + c2*s1*x1 - s1*s2*y1*z2 + s1*s2*y2*z1)*i
+ (c1*s2*y2 + c2*s1*y1 + s1*s2*x1*z2 - s1*s2*x2*z1)*j
+ (c1*s2*z2 + c2*s1*z1 - s1*s2*x1*y2 + s1*s2*x2*y1)*k
#+end_example

From here we can directly read out the claim! QED.

**** Exercise 4.16
What is the 4×4 unitary matrix for the following circuits

#+RESULTS: exercise-4.16-appendix
#+begin_example

q_0: ─────
     ┌───┐
q_1: ┤ H ├
     └───┘

     ┌───┐
q_0: ┤ H ├
     └───┘
q_1: ─────

#+end_example

***** Solution
According the convention of the book, these two circuits are represented by $I\otimes H$,
$H\otimes I$ (in that order). We note here that Qiskit uses the reverse order. The Kronecker Product
yields the matrices (since the basis vectors are ordered in a canonical way: 00, 01, 10, 11):

$$
  I\otimes H = \frac{1}{\sqrt{2}}
  \,\begin{bmatrix}
    1 &  1 & 0 &  0 \\
    1 & -1 & 0 &  0 \\
    0 &  0 & 1 &  1 \\
    0 &  0 & 1 & -1
  \,\end{bmatrix}
$$

$$
  H\otimes I = \frac{1}{\sqrt{2}}
  \,\begin{bmatrix}
    1 & 0 &  1 &  0 \\
    0 & 1 &  0 &  1 \\
    1 & 0 & -1 &  0 \\
    0 & 1 &  0 & -1
  \,\end{bmatrix}
$$

***** Appendix
Code which produces the circuits:

#+name: exercise-4.16-appendix
#+begin_src python :results replace
  qc1 = QuantumCircuit(2)
  qc1.h(1)

  qc2 = QuantumCircuit(2)
  qc2.h(0)

  str(qc1.draw('text')) + "\n\n" + str(qc2.draw('text'))
#+end_src

**** Exercise 4.17
Construct a =CNOT= (CX) gate from a =CZ= using two Hadamard Gates.

***** Solution
The general form of a CU-gate is ($P_j$ being projections):

$$
  \CU = P_1 \otimes I + P_2 \otimes U
$$

Hence by $HZH=X$:

$$
  CX = I\otimes H \cdot CZ \cdot I\otimes H
$$

**** Exercise 4.18
Show that swapping the two qubits leaves $\CZ$ invariant. That is, these two circuits are equal:

#+begin_example

q_0: ──■──
     ┌─┴─┐
q_1: ┤ Z ├
     └───┘

     ┌───┐
q_0: ┤ Z ├
     └─┬─┘
q_1: ──■──
#+end_example

For this reason, the $CZ$ is often denoted in a symmetric form:

#+RESULTS: exercise-4.18-appendix
:
: q_0: ─■─
:       │
: q_1: ─■─
:


***** Proof
This follows from

$$
  \CZ = P_1 \otimes I + P_2 \otimes Z = I \otimes P_1 + Z \otimes P_2 .
$$

***** Appendix
Code which produces the circuits (at least the plot of the symmetric CZ gate):

#+name: exercise-4.18-appendix
#+begin_src python :results replace
  qc = QuantumCircuit(2)
  qc.cz(0, 1)

  qc.draw('text')
#+end_src

**** Exercise 4.19
The gate is a simple permutation whose action on a density matrix ρ is to rearrange the elements in
the matrix. Write out this action explicitly in the computational basis.

***** Solution
The density matrix for two qubits in the computational basis looks as follows:

$$
  \rho = \sum_{i,j=0}^1 p_{ij} |ij\rangle .
$$

$\CX$ maps $|0j\rangle$ to itself, and it swaps $|10\rangle$ with $|11\rangle$. Hence, as a mapping
on the density matrix it acts as follows on the density matrix:

$$
  p_{0i} \mapsto p_{0i},\quad p_{10} \mapsto p_{11},\quad p_{11} \mapsto p_{10} .
$$

**** Exercise 4.20
Show that the following two circuits are equal:

#+RESULTS: exercise-4.20-appendix
#+begin_example
     ┌───┐     ┌───┐
q_0: ┤ H ├──■──┤ H ├
     ├───┤┌─┴─┐├───┤
q_1: ┤ H ├┤ X ├┤ H ├
     └───┘└───┘└───┘

     ┌───┐
q_0: ┤ X ├
     └─┬─┘
q_1: ──■──

#+end_example


Moreover the effect of the CX gate on the eigenbasis of $X$ is as follows:

$$
  \,|\pm+\rangle \mapsto |\pm+\rangle,\quad |\pm-\rangle \mapsto |\mp-\rangle
$$

In other words: With respect to the eigenbasis of $X$ the CX gate acts again like a CX gate but with
the control and target qubit switched.

# TODO: make drawings of the circuits.

***** Proof
The statement after "Moreover" is direct consequence of the first statement. Therefore we only prove
the first one.

We have to show that $H\otimes H \cdot CX \cdot H\otimes H$ is the CX gate with the qubits reversed.

First, let us recall the projections on the eigenbasis of $X$:

\begin{align*}
  P_+ &= |+\rangle \otimes \langle+| = \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}, \\
  P_- &= |-\rangle \otimes \langle-| = \begin{bmatrix} 1 & -1 \\ -1 & 1 \end{bmatrix}.
\end{align*}

Consider

$$
  H\otimes H \cdot CX \cdot H\otimes H = P_+ \otimes I + P_- \otimes Z .
$$

We have to show that, after swapping the two qubits the RHS equals $CX$. In fact:

$$
  I \otimes P_+ + Z \otimes P_- = \frac{1}{2}
      \,\begin{bmatrix}
         1 &  1 &  0 &  0 \\
         1 &  1 &  0 &  0 \\
         0 &  0 &  1 &  1 \\
         0 &  0 &  1 &  1
      \,\end{bmatrix}
    \,+ \frac{1}{2}
      \,\begin{bmatrix}
         1 & -1 &  0 &  0 \\
        -1 &  1 &  0 &  0 \\
         0 &  0 & -1 &  1 \\
         0 &  0 &  1 & -1
      \,\end{bmatrix}
    =
      \,\begin{bmatrix}
        1 & 0 & 0 & 0 \\
        0 & 1 & 0 & 0 \\
        0 & 0 & 0 & 1 \\
        0 & 0 & 1 & 0
      \,\end{bmatrix} = \CX .
$$

***** Appendix
Code which produces the circuits:

#+name: exercise-4.20-appendix
#+begin_src python :results replace
  qc1 = QuantumCircuit(2)
  qc1.h(0)
  qc1.h(1)
  qc1.cx(0, 1)
  qc1.h(0)
  qc1.h(1)

  qc2 = QuantumCircuit(2)
  qc2.cx(1, 0)

  str(qc1.draw('text')) + "\n\n" + str(qc2.draw('text'))
#+end_src

**** Exercise 4.21
Verify that Figure 4.8 implements the $C^2(U)$ operation.

***** Solution
The easiest solution might be to just try out all four possibilities to plugin the computational
basis into the first two wires.

Another approach is to just calculate the corresponding algebraic expression:

\begin{align*}
        &(P_0 \otimes I \otimes I + P_1 \otimes I \otimes V) \\
  \cdot &(P_0 \otimes I \otimes I + P_1 \otimes X \otimes I) \\
  \cdot &(I \otimes P_0 \otimes I + I \otimes P_1 \otimes V^\dagger) \\
  \cdot &(P_0 \otimes I \otimes I + P_1 \otimes X \otimes I) \\
  \cdot &(I \otimes P_0 \otimes I + I \otimes P_1 \otimes V)
\end{align*}

Using $XP_0X=P_1$ and $XP_1X=P_0$ we get, that this is:

$$
  P_0 \otimes P_0 \otimes I + P_1 \otimes P_0 \otimes I + P_0 \otimes P_1 \otimes I + P_1 \otimes P_1 \otimes V^2 .
$$

Which is indeed $C^2(U)$.

**** Exercise 4.22
Prove that a $C^2(U)$ gate (for any single qubit unitary $U$) can be constructed using at most eight
one-qubit gates, and six $\CX$.

***** Proof
If we combine the construction of $C^2(U)$ from figure 4.8 (the $U=V^2$ thing) with the construction
of $C(U)$ from figure 4.6 (the $AXBXC=U$ thing), we immediately see that we can construct a circuit
with six $CX$ and ten one-qubit gates (two of the three phase gates cancel each other). However, we
can reduce the number of one qubit gates by two, since two pairs can actually be merged into a
single one-qubit operator.

**** Exercise 4.23
Construct a $C^1(U)$ gate for $U=R_x(\theta)$ and $U=R_y(\theta)$, using only CNOT and single qubit
gates. Can you reduce the number of single qubit gates needed in the construction from three to two?

***** Solution
For the y-rotation this is easy:

$$
  C^1(R_y(\theta)) = \CX \cdot R_{y,2}(-\theta/2) \cdot \CX \cdot R_{y,2}(\theta/2) .
$$

#+RESULTS: exercise-4.22-appendix-1
:
: q_0: ─────────────■────────────────■──
:      ┌─────────┐┌─┴─┐┌──────────┐┌─┴─┐
: q_1: ┤ Rx(θ/2) ├┤ X ├┤ Rx(-θ/2) ├┤ X ├
:      └─────────┘└───┘└──────────┘└───┘

We get the same result if we use the proof of Corollary 4.2. For the x-rotation we first deduce from
exercise 4.6 (interpretation as 3D rotations):

$$
  R_x(\theta) = R_z(-\pi/2) \cdot R_y(\theta) \cdot R_z(\pi/2) .
$$

Now the proof of Corollary 4.2 shows:

$$
  C^1(R_x(\theta)) = R_{z,2}(-\pi/2) \CX \cdot R_{y,2}(-\theta/2) \cdot \CX \cdot R_{z,2}(-\pi/2) R_{y,2}(\theta/2) .
$$

#+RESULTS: exercise-4.22-appendix-2
:
: q_0: ─────────────────────────■────────────────■──────────────
:      ┌─────────┐┌──────────┐┌─┴─┐┌──────────┐┌─┴─┐┌──────────┐
: q_1: ┤ Ry(θ/2) ├┤ Rz(-π/2) ├┤ X ├┤ Ry(-θ/2) ├┤ X ├┤ Rz(-π/2) ├
:      └─────────┘└──────────┘└───┘└──────────┘└───┘└──────────┘

***** Appendix
The code for the circuit plots:

#+name: exercise-4.22-appendix
#+begin_src python :exports code
  params = (Param('θ/2'), Param('-θ/2'), Param('-π/2'))

  qc1 = QuantumCircuit(2)
  qc1.rx(params[0], 1)
  qc1.cx(0, 1)
  qc1.rx(params[1], 1)
  qc1.cx(0, 1)

  qc2 = QuantumCircuit(2)
  qc2.ry(params[0], 1)
  qc2.rz(params[2], 1)
  qc2.cx(0, 1)
  qc2.ry(params[1], 1)
  qc2.cx(0, 1)
  qc2.rz(params[2], 1)
#+end_src

#+name: exercise-4.22-appendix-1
#+begin_src python :results replace :exports both
  str(qc1.draw('text'))
#+end_src

#+name: exercise-4.22-appendix-2
#+begin_src python :results replace :exports both
  str(qc2.draw('text'))
#+end_src

**** Exercise 4.24
Verify that Figure 4.9 implements the Toffoli gate.

***** Proof
Preliminaries: Recall that $T=e^{i\pi/8}R_z(\pi/4)$ and $XZX=-Z$. It suffices to prove the claim for
states of the form $|ij\rangle\otimes|\psi\rangle$ (the basis states in the first two wires), by
linearity.

The first wire always acts as $T$. This does nothing to $|0\rangle$ and applies a phase shift to $|1\rangle$.

Now we consider the first two wires (the upper wires) states of the form $|01\rangle$ (that is, the
control qubit is turned off). Then, the second wire acts as $ST^\dagger T^\dagger=I$. Hence
$|01\rangle$ is mapped to itself. Now consider $|1i\rangle$. The second wire now acts as

$$
  SX T\dagger XT\dagger = e^{-i\pi/4} S XR_z(\pi/4)XR_z(\pi/4) = e^{-i\pi/4} S .
$$

Hence $|1i\rangle$ is mapped to $|1\rangle\otimes S|i\rangle$. We summarize: The first two wires act as:

$$
  \,|ij\rangle \mapsto \begin{cases}
      i|11\rangle  & \text{if } i=j=1 \\
      \,|ij\rangle & \text{else.}
  \,\end{cases}
$$

Now consider the third wire. It is not hard to see that if one of the first two qubits is
$|0\rangle$, then all operators cancel each other (equalize to $I$) due to $X^2=-1$ and $T^\dagger T=I$.

So the only interesting case is if the first to qubits are both on (equal state 1). In that case we
have to show that the operator in the third row is equal to $-iX$. We have:

$$
  T X T^\dagger X = R_z(\pi/4) X R_z(-\pi/4) X = R_z(\pi/2) .
$$

Hence the operator in the third row is:

$$
  H R_z(\pi/2) R_z(\pi/2) H = R_x(\pi) = -iX.
$$

QED.

**** TODO Exercise 4.25 [3/4]
Recall that the Fredkin (controlled-swap) gate performs the transform:

\begin{bmatrix}
  1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
  0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
  0 & 0 & 0 & 0 & 0 & 0 & 0 & 1
\end{bmatrix}


1. [X] Give a quantum circuit which uses three Toffoli gates to construct the Fredkin gate (Hint: think
   of the swap gate construction – you can control each gate, one at a time).
2. [X] Show that the first and last Toffoli gates can be replaced by gates.
3. [X] Now replace the middle Toffoli gate with the circuit in Figure 4.8 to obtain a Fredkin gate
   construction using only six two-qubit gates.
4. [ ] Can you come up with an even simpler construction, with only five two-qubit gates?

***** Solution to 1
Taking the swap-gate construction from Figure 1.7 we may deduce that the following circuit might do
what we want:

#+RESULTS: exercise-4-25-appendix-1
:
: q_0: ──■────■────■──
:        │  ┌─┴─┐  │
: q_1: ──■──┤ X ├──■──
:      ┌─┴─┐└─┬─┘┌─┴─┐
: q_2: ┤ X ├──■──┤ X ├
:      └───┘     └───┘

In fact, a short calculation yields the desired result.

#+begin_src python
  T01 = make_CnU(3, [0, 1], 2, X)
  T02 = make_CnU(3, [0, 2], 1, X)

  assert T01 * T02 * T01 == Fred, "Exercise 4.25, Solution to 1."
#+end_src

***** Solution to 2
The following circuit equals the Fredkin Gate too:

#+RESULTS: exercise-4-25-appendix-2
:
: q_0: ───────■───────
:           ┌─┴─┐
: q_1: ──■──┤ X ├──■──
:      ┌─┴─┐└─┬─┘┌─┴─┐
: q_2: ┤ X ├──■──┤ X ├
:      └───┘     └───┘

In fact:

#+begin_src python
  C12 = make_CU(3, 1, 2, X)

  assert C12 * T02 * C12 == Fred, "Exercise 4.25, Solution to 2."
#+end_src

***** Solution to 3
Apriori this new circuit uses 8 = 6 + 2 two-qubit gates. However the first two of these can be
merged into one (together with the Hadamard in between). Observe that the a similar fact is true for
the last two two-qubit gates of the construction from Figure 4.9. Hence we only need 6 such gates.

***** Solution to 4
So far I have no solution. My first guess was to use the construction from Firgure 4.8 (the thing
with $V^2=X$). With the same trick as in Solution 3 (merging adjacent gates) one gets a solution
with 6 two-qubit gates. I tried to move around gates at the right end (via commutator relations)
hoping the find an equivalent circuit with on gate less - so far without success.

***** Appendix
This code produces the images to the solutions.

#+name: exercise-4-25-appendix-1
#+begin_src python :results replace :exports both
  qc1 = QuantumCircuit(3)
  qc1.ccx(0, 1, 2)
  qc1.ccx(0, 2, 1)
  qc1.ccx(0, 1, 2)

  qc1.draw('text')
#+end_src

#+name: exercise-4-25-appendix-2
#+begin_src python :results replace :exports both
  qc2 = QuantumCircuit(3)
  qc2.cx(1, 2)
  qc2.ccx(0, 2, 1)
  qc2.cx(1, 2)

  qc2.draw('text')
#+end_src

**** Exercise 4.26
Show that the circuit

#+RESULTS: exercise-4-26-appendix
:
: q_0: ─────────────────────────────■───────────────────────────────
:                                   │
: q_1: ─────────────■───────────────┼────────────────■──────────────
:      ┌─────────┐┌─┴─┐┌─────────┐┌─┴─┐┌──────────┐┌─┴─┐┌──────────┐
: q_2: ┤ Ry(π/?) ├┤ X ├┤ Ry(π/?) ├┤ X ├┤ Ry(-π/?) ├┤ X ├┤ Ry(-π/?) ├
:      └─────────┘└───┘└─────────┘└───┘└──────────┘└───┘└──────────┘

differs from a Toffoli gate only by relative phases $e^{i\theta(c_1,c_2,t)}$.

***** Proof
The following code saves us from the tedious calculations. It shows that $?=4$ (everywhere) is a
possible choice and that

$$
  \theta(c_1, c_2, t) = \begin{cases}
      \pi  & \text{if } c_1=1,  \text{ and } c_2=t=0 \\
      0 & \text{else.}
  \,\end{cases}
$$

#+name: exercise-4-8-get-circuit
#+begin_src python
  def get_circuit(n: int):
      """The n is the divisor missing in the Figure of Exercise 4.26."""
      R = tprod(Id, Id, Ry.subs(theta, pi / n))
      Ri = tprod(Id, Id, Ry.subs(theta, -pi / n))

      CX12 = make_CU(3, 1, 2, X)
      CX02 = make_CU(3, 0, 2, X)

      return sp.simplify(R * CX12 * R * CX02 * Ri * CX12 * Ri)


  C = get_circuit(4)
  Phase = tprod(Id, Id, Id) - 2*tprod(P1, P0, P0)  # Multiplies |100> by -1

  assert Phase * C == Toff, "Exercise 4.26: Circuit should be Toffoli up to Phase Factor"
#+end_src

***** Appendix
This code produces the images to the problem.

#+name: exercise-4-26-appendix
#+begin_src python :results replace :exports both
  qc = QuantumCircuit(3)
  params = (Param('π/?'), Param('-π/?'))
  qc.ry(params[0], 2)
  qc.cx(1, 2)
  qc.ry(params[0], 2)
  qc.cx(0, 2)
  qc.ry(params[1], 2)
  qc.cx(1, 2)
  qc.ry(params[1], 2)

  qc.draw('text')
#+end_src

**** Exercise 4.27
Using just CNOTs and Toffoli gates, construct a quantum circuit to perform the transformation

\begin{bmatrix}
  1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
  0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
  0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
  0 & 0 & 0 & 0 & 0 & 0 & 1 & 0
\end{bmatrix}

This kind of partial cyclic permutation operation will be useful later, in Chapter 7.

***** Solution
Since the exercise already speaks about permutations lets dive into the permutation group
formalism. This works since all involved matrices (CNOT, Toffoli, and the matrix from the exercise
text) are all /permutation matrices/. These form a group which is isomorphic to a group of
permuations. The procedure below also works analogously if we would directly use the matrix
representations but I think it is nice to think it throught in a different formalism.

Keep in mind that the isomorphism reverses the order of multiplication, that is: if Matrices $A$ and
$B$ correspond to permutations $a$ and $b$ then $AB$ corresponds to $ba$ (meaning apply $b$ first
and then $a$). This is not just a sympy quirk but a normal convention in the mathematics of
permutations. Maybe the rationale is that the action of a permutation is sometimes written in
superscript notation: $x^{ba}=(x^b)^a$ where $x$ is some set which gets permutated (see also
[[https://en.wikipedia.org/wiki/Group_action#Right_group_action][right-group-action]] on wikipedia, which does not use superscript notation though).

Recall the Matrix representation for the =CNOT= gate with control at 0 and target at 1 (on three
wires):

$$
  \CX_{01} = \begin{bmatrix}
      1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
      0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
      0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
      0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 & 1 & 0 & 0
    \,\end{bmatrix}
$$

If we enumerate the basis vectors from $0$ (for $|000\rangle$) to $7$ (for $|111\rangle$), then this
corresponds to the permuation $(4\;6)(5\;7)$ (in [[https://en.wikipedia.org/wiki/Permutation#Cycle_notation][cycle-notation]]). The other variations of $\CX$ (with
different control/target) can be found by noting that permuting the three wires induces a
permutation on the basis vectors which in turn translates to an action on the permutation group
itself. See the code block below for the results (or use ~make_CU~ to make life easier).

The "standard" Toffoli Gate is the one with target at 2:

$$
  T_2 = \begin{bmatrix}
      1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
      0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
      0 & 0 & 0 & 0 & 0 & 0 & 1 & 0
  \,\end{bmatrix} ,
$$

which corresponds to the permuation $(6\;7)$. The other three Toffolis (with different targets) are
listed in the code block below.

#+name: exercise-4-27-1
#+begin_src python
  # cxij means control i, target j
  cx01 = Perm(4, 6)(5, 7)
  cx02 = Perm(4, 5)(6, 7)
  cx12 = Perm(2, 3)(6, 7)
  cx10 = Perm(2, 6)(3, 7)
  cx20 = Perm(1, 5)(3, 7)
  cx21 = Perm(1, 3)(5, 7)

  # ti means: target at qubit i
  t0 = Perm(3, 7)
  t1 = Perm(5, 7)
  t2 = Perm(6, 7)
#+end_src

The following code defines an exhaustive search for solutions with a fixed number of gates.

#+name: exercise-4-27-2
#+begin_src python
  perms = [cx01, cx02, cx12, cx10, cx20, cx21, t0, t1, t2]
  names = ["cx01", "cx02", "cx12", "cx10", "cx20", "cx21", "t0", "t1", "t2"]
  indices = list(range(len(perms)))

  def search_ex4_27(n: int):
      """Find all solutions to exercise 4.27 with n gates."""
      for idxs in product(*([indices]*n)):
          ps = [perms[i] for i in idxs]
          prod = reduce((lambda x, y: x*y), ps)
          if prod == Perm(1, 2, 3, 4, 5, 6, 7):
              print(" * ".join([names[i] for i in idxs]))
#+end_src

Trying out some values of $n$ we see that $n=5$ is the minimal value which yields a solution. There
are six solutions in fact but they are similar in the sense that the last three permutations (gates)
actually commute. The solutions are:

#+begin_example
t0 * cx21 * cx02 * cx12 * t2
t0 * cx21 * cx02 * t2 * cx12
t0 * cx21 * cx12 * cx02 * t2
t0 * cx21 * cx12 * t2 * cx02
t0 * cx21 * t2 * cx02 * cx12
t0 * cx21 * t2 * cx12 * cx02
#+end_example

One benefit of the "reversed" multiplication of the permutations is that it is the same ordering
like in typical drawings of circuits. Let us just draw the third one:

#+RESULTS: exercise-4-27-appendix
:      ┌───┐
: q_0: ┤ X ├────────────■────■──
:      └─┬─┘┌───┐       │    │
: q_1: ──■──┤ X ├──■────┼────■──
:        │  └─┬─┘┌─┴─┐┌─┴─┐┌─┴─┐
: q_2: ──■────■──┤ X ├┤ X ├┤ X ├
:                └───┘└───┘└───┘

***** Appendix
This code produces the circuit drawings.

#+name: exercise-4-27-appendix
#+begin_src python :results replace :exports both
  qc = QuantumCircuit(3)
  qc.ccx(1, 2, 0)
  qc.cx(2, 1)
  qc.cx(1, 2)
  qc.cx(0, 2)
  qc.ccx(0, 1, 2)

  qc.draw('text')
#+end_src

**** Exercise 4.28
*Original Formulation:* For $U=V^2$ with $V$ unitary, construct a $C^5(U)$ gate analogous to that in
Figure 4.10, but using no work qubits. You may use controlled-$V$ and controlled-$V^\dagger$ gates.

*Remark:* In my opinion the formulation of the exercise is bad. The way I understand it there is
indeed no solution. Some sources in the internet claim that some slight variation of the circuit in
Figure 8 (for n=3 add a wire above the others, and let this wire be an additional control of the two
CX and the rightmost CV) solves the problem (see reference in the solution). But in fact, I also
found this solution but since it involves a $C^{n-1}V$ gate to construct $C^nU$ I rejected it as an
invalid solution. To get rid of all these control qubits on $V$ one would again take further roots
of $V$ which seems to be not very usefull for a real implementations. So at best it is a *pseudo
solution* (in my opinion).

*Alternate Version:* Let $n\geq3$, $V$ unitary and $U=V^2$. Prove that it is impossible to obtain a
construction of $C^n(U)$ on $n+1$ wires from $X$, $V$, $V^\dagger$, $U$, $C(X)$, $C(V)$,
$C(V^\dagger)$, and $C(U)$ alone which works for arbitrary $U$ (for $n=2$ it is possible as Figure
4.8 shows).

***** Proof (of the alternate version)
The idea for the proof is surprisingly simple - watch out for the determinant of the circuit! The
credits for the idea go to [[https://cs.stackexchange.com/q/138853][this stackoverflow answer]]. The overall discussion contains also a
reference to the pseudo-solution mentioned in the remark above.

Consider $n+1$ wires and recall that with all controls being on the first $n$ wires we have:

$$
  C^n(U) = \mathrm{diag}(I,I,\ldots,I,U) \text{ with } 2^n - 1 \text{ copies of }
  I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}.
$$

That is, $C^n(U)$ is a diagonal matrix up to a tiny 2 by 2 sub-matrix $U$ in the lower right
corner. This follows from the ordering of the basis vectors (counting in binary, like 000, 001, 010,
..., 111). Hence:

$$
  \det(C^n(U)) = \det(U).
$$

Note that this formula also holds if the controls are elsewhere. This follows from the fact that the
determinant is invariant with respect to a change of basis.

Now consider the more general case of $C^m(W)$ (for a unitary $W$) with $m\leq n$ on $n+1$
wires. Assume for the moment that $W$ sits on the last wire and the controls being immediately
before. Again by the ordering of the basis vectors we see that:

$$
  C^m(W) = \mathrm{diag}(W_m, W_m,\ldots, W_m) \text{ with } 2^{n-m} \text{ copies of } W_m,
$$

where $W_m$ looks like in the special case $m=n$ above. Since the determinant of $W_m$ is $\det(W)$, we deduce:

$$
  \det(C^m(W)) = \det(W)^{2^{n-m}} .
$$

Again this still holds if the controls and the target are elsewhere on the $n$ wires.

Now suppose the construction was possible:

$$
  C^n(U) = \prod_i G_i,
$$

where each $G_i$ is one of the allowed gates. By well known properties of the determinant we have:

$$
  \det(U) = \prod_i \det(G_i) .
$$

The analysis above, together with $n-m\geq 2$, shows that $\det(G_i)=\det(W)^{4k}$ for some $k$ and
$W$ one of $V$, $V^\dagger$, $U$ or $X$. Since $\det(X)=-1$ we have:

$$
  \det(U) = \left(\det(V)^{k_V} \cdot \det(V^\dagger)^{k_{V^\dagger}} \cdot \det(U)^{k_U}\right)^4.
$$

This can't be satisfied for /arbitrary/ $U$. To be specific consider $U=X$. In that case the LHS is
$-1$ and the RHS is $+1$ because $\det(V),\det(V^\dagger)\in\{+i,-i\}$. QED.

**** TODO Exercise 4.29
Find a circuit containing $O(n^2)$ Toffoli, =CNOT= and single qubit gates which implements a
$C^n(X)$ gate (for $n>3$), using no work qubits.

*TODO:* In the light of the discussion of Exercise 4.28 this seems to be not possible - at least how
I interpret the exercise. Maybe one can find a different interpretation, state the exercise less
vague, and give a solution.

**** TODO Exercise 4.30
Suppose $U$ is a single qubit unitary operation. Find a circuit containing $O(n^2)$ Toffoli, =CNOT= and single
qubit gates which implements a $C^n(U)$ gate (for $n>3$), using no work qubits.

*TODO:* In the light of the discussion of Exercise 4.28 this seems to be not possible - at least how
I interpret the exercise. Maybe one can find a different interpretation, state the exercise less
vague, and give a solution.

**** Exercise 4.31
Let subscripts denote which qubit an operator acts on, and let $C$ be a =CNOT= with qubit 1 the
control qubit and qubit 2 the target qubit. Prove the following identities:

\begin{align}
  C X_1 C &= X_1 X_2 \\
  C Y_1 C &= Y_1 X_2 \\
  C Z_1 C &= Z_1 \\
  C X_2 C &= X_2 \\
  C Y_2 C &= Z_1 Y_2 \\
  C Z_2 C &= Z_1 Z_2 \\
  R_{z,1}(\theta) C &= C R_{z,1}(\theta) \\
  R_{x,2}(\theta) C &= C R_{x,2}(\theta)
\end{align}

***** Proofs
Preparations: Let $N$ stand for $X$, $Y$, or $Z$. Recall that $P_0$ and $P_1$ are the projections
onto the computational basis, and that:

\begin{align*}
  C = P_0 \otimes I + P_1 \otimes X \\
  N_1 = N \otimes I,\quad N_2 = I \otimes N
\end{align*}

In particular: $X_1 X_2=X\otimes X$.

Identity (1) follows by considering only states of the form $|0j\rangle$, $|1j\rangle$, noting that
$X_1$ swaps the computational basis.

Identitiy (2) follows similarly if one observes that $Y_1$ acts like $X_1$ up to different phases,
which do not play a role here.

Identity (3) follows from the fact that $Z_1$ commutes with $P_0$ and $P_1$ (and hence with $C$),
and that $C^2=I$.

Identity (4) follows similarly from the fact that $X_2$ also commutes with $C$.

Identity (5) follows from $YX=-iZ=-XY$, and $P_0P_1=P_1P_0=0$, and $X^2=I$, and $Z=P_0-P_1$.

Identity (6) follows the same way as (5).

Identity (7) follows from the fact that $Z$, and hence $R_z$, commutes with $P_0$ and $P_1$.

Identitiy (8) follows from the fact $X$, and hence $R_x$, commutes with $X$.

** Chapter 5
  :PROPERTIES:
  :header-args:python: :session *chapter-5* :tangle yes :comments link :results silent
  :END:
*** notes
#+name: dummy
#+begin_src python :results replace
  test = 123
  test
#+end_src

#+RESULTS: dummy
: 123

* References
#+print_bibliography:
