#+title: Solutions for the bible of Quantum Computation and Quantum Information
#+author: Reinhard Stahn

This repository contains solutions to most exercises of the Book `Quantum Computation and Quantum
Information` by Michael A. Nielsen & Isaac L. Chuang (Mike and Ike). The easiest way to view the
solutions is to head over to [[https://rainij.github.io/solutions-qcqi-nielsen-chuang/][the website]] which is generated from this repo via GitHub pages.

* How to use the sources
The sources of the website are (mostly) under [[./src/]]. The entry point is the [[https://orgmode.org/][org-mode]] file
[[./src/index.org]]. The sources contain more information than what is displayed on the website. In
particular they contain the [[https://qiskit.org/][qiskit]] code to generate the numerous drawings of circuits.

Most reasonable text editors have at least an addon to display org files (e.g. [[https://vscode-org-mode.github.io/vscode-org-mode/][vscode]]). But you
probably need [[https://www.gnu.org/software/emacs/][Emacs]] for more sophisticated things like execution or tangling of the embedded python
or sage code.

To use the embedded code without modifying the org files you can do the following /as an
Emacs and IPython/Sagemath user/:

- open one of the org files (e.g. [[./src/utils.org]]),
- execute ~M-x org-babel-tangle~, which produces sage or python files,
- open your =ipython= or =sage= shell and run the generated file using e.g. ~%run
  utils.py~ (ipython) or ~attach("utils.sage")~ (sage).

I can't guarantee that the code does not contain bugs. For /some/ functionality I
implemented unit tests (=pytest=) which are run by github actions right before every
deploy. But I /do not/ try to be as rigorous as in a serious industry relevant software
project - I have no time for this and it is not really needed for such a small educational
project.

* Contributing
It is unclear if anybody wants to contribute anything to this project. Just in case, here is what
you need to know ...

/At the moment/ I do not accept solutions to exercises which do not already appear in my
notes. I use these exercises to prepare for a job in the quantum industry which I will
start in 2024 so I want to solve them on my own.

But if you find mistakes you can let me know or open a pull request.

In any case, contributors must be fine dedicating their work to the public domain (see the [[#unlicense][section
on unlicense]]). To keep things simple, any contribution is implicitly assumed to agree to this.

* Unlicense
:PROPERTIES:
:CUSTOM_ID: unlicense
:END:
This work has been dedicated to the [[https://en.wikipedia.org/wiki/Public_domain][public domain]]. See the [[file:UNLICENSE][UNLICENSE]] file and have a look into
https://unlicense.org/. Attribution is appreciated, but not required.

Small parts of this work are under a different /free/ license. E.g. pictures I didn't produce
myself. If necessary by the respective license I indicate this at an appropriate place.
