# TODO: currently we have to refer #+include (for HTML export) and #+setupfile (for latex preview)
# this file. This looks weird in the files where this is done. Can we do better?

#+name: insert-latex-macros-function-for-dynamic-block
#+begin_src emacs-lisp :results silent :exports none
  (defun org-dblock-write:insert-latex-macros (params)
    "Function of the dynamic block for latex macros."
    (let ((lines nil) (file (plist-get params :file)))
        (with-temp-buffer
            (insert-file-contents file)
            (setq lines (split-string (buffer-string) "\n" t)))
        (insert (mapconcat (lambda (str) (concat "#+latex_header: " str)) lines "\n"))
        (insert "\n#+begin_export html\n\\[\n")
        (insert (mapconcat 'identity lines "\n"))
        (insert "\n\\]\n#+end_export")))
#+end_src

# This dynamic block defines the relevant latex macros so that org mode catches them up. Define new
# macros in ./latex-macros.tex. Execute org-dblock-update to sync with latex-macros.tex. Don't
# forget to execute the source block of org-dblock-write:insert-latex-macros before!
#+BEGIN: insert-latex-macros :file "../latex-macros.tex"
#+latex_header: \newcommand{\BB}{\mathbb{B}}
#+latex_header: \newcommand{\CC}{\mathbb{C}}
#+latex_header: \newcommand{\HH}{\mathbb{H}}
#+latex_header: \newcommand{\KK}{\mathbb{K}}
#+latex_header: \newcommand{\NN}{\mathbb{N}}
#+latex_header: \newcommand{\QQ}{\mathbb{Q}}
#+latex_header: \newcommand{\RR}{\mathbb{R}}
#+latex_header: \newcommand{\ZZ}{\mathbb{Z}}
#+latex_header: \newcommand{\ii}{\mathrm{i}}
#+latex_header: \newcommand{\jj}{\mathrm{j}}
#+latex_header: \newcommand{\kk}{\mathrm{k}}
#+latex_header: \newcommand{\dd}{\mathrm{d}}
#+latex_header: \newcommand{\FT}{\mathcal{F}} % Fourier Transform
#+latex_header: \newcommand{\tto}{\twoheadrightarrow}
#+latex_header: \newcommand{\inv}{^{-1}}
#+latex_header: \newcommand{\RF}{\mathrm{RF}}
#+latex_header: \newcommand{\sys}{\mathrm{sys}}
#+latex_header: \newcommand{\diag}{\mathrm{diag}}
#+latex_header: \newcommand{\calE}{\mathcal{E}}
#+latex_header: \newcommand{\calF}{\mathcal{F}}
#+latex_header: \newcommand{\calH}{\mathcal{H}}
#+latex_header: \newcommand{\calR}{\mathcal{R}}
#+latex_header: \newcommand{\abs}[1]{\left|#1\right|}
#+latex_header: \newcommand{\norm}[1]{\|#1\|}
#+latex_header: \newcommand{\sprod}[2]{\langle#1|#2\rangle} % deprecated, use braket instead.
#+latex_header: \newcommand{\braket}[2]{\langle#1|#2\rangle} % scalar product
#+latex_header: \newcommand{\ptrace}[2]{\mathrm{tr}_{#1}\left(#2\right)}
#+latex_header: \newcommand{\trace}[1]{\mathrm{tr}\left(#1\right)}
#+latex_header: \newcommand{\rank}[1]{\mathrm{rank}\left(#1\right)}
#+latex_header: \newcommand{\floor}[1]{\lfloor#1\rfloor}
#+latex_header: \newcommand{\ceil}[1]{\lceil#1\rceil}
#+latex_header: \newcommand{\bra}[1]{\langle#1|}
#+latex_header: \newcommand{\ket}[1]{|#1\rangle}
#+latex_header: \newcommand{\proj}[1]{\ket{#1}\bra{#1}}
#+latex_header: \newcommand{\mean}[1]{\langle#1\rangle}
#+latex_header: \newcommand{\wt}[1]{\mathrm{wt}\left(#1\right)}
#+latex_header: \newcommand{\prob}[1]{\mathrm{Prob}\left[#1\right]}
#+latex_header: \newcommand{\orac}{\mathrm{Orac}}
#+latex_header: \newcommand{\?}{} % sometimes I need just a separator other than whitespace
#+begin_export html
\[
\newcommand{\BB}{\mathbb{B}}
\newcommand{\CC}{\mathbb{C}}
\newcommand{\HH}{\mathbb{H}}
\newcommand{\KK}{\mathbb{K}}
\newcommand{\NN}{\mathbb{N}}
\newcommand{\QQ}{\mathbb{Q}}
\newcommand{\RR}{\mathbb{R}}
\newcommand{\ZZ}{\mathbb{Z}}
\newcommand{\ii}{\mathrm{i}}
\newcommand{\jj}{\mathrm{j}}
\newcommand{\kk}{\mathrm{k}}
\newcommand{\dd}{\mathrm{d}}
\newcommand{\FT}{\mathcal{F}} % Fourier Transform
\newcommand{\tto}{\twoheadrightarrow}
\newcommand{\inv}{^{-1}}
\newcommand{\RF}{\mathrm{RF}}
\newcommand{\sys}{\mathrm{sys}}
\newcommand{\diag}{\mathrm{diag}}
\newcommand{\calE}{\mathcal{E}}
\newcommand{\calF}{\mathcal{F}}
\newcommand{\calH}{\mathcal{H}}
\newcommand{\calR}{\mathcal{R}}
\newcommand{\abs}[1]{\left|#1\right|}
\newcommand{\norm}[1]{\|#1\|}
\newcommand{\sprod}[2]{\langle#1|#2\rangle} % deprecated, use braket instead.
\newcommand{\braket}[2]{\langle#1|#2\rangle} % scalar product
\newcommand{\ptrace}[2]{\mathrm{tr}_{#1}\left(#2\right)}
\newcommand{\trace}[1]{\mathrm{tr}\left(#1\right)}
\newcommand{\rank}[1]{\mathrm{rank}\left(#1\right)}
\newcommand{\floor}[1]{\lfloor#1\rfloor}
\newcommand{\ceil}[1]{\lceil#1\rceil}
\newcommand{\bra}[1]{\langle#1|}
\newcommand{\ket}[1]{|#1\rangle}
\newcommand{\proj}[1]{\ket{#1}\bra{#1}}
\newcommand{\mean}[1]{\langle#1\rangle}
\newcommand{\wt}[1]{\mathrm{wt}\left(#1\right)}
\newcommand{\prob}[1]{\mathrm{Prob}\left[#1\right]}
\newcommand{\orac}{\mathrm{Orac}}
\newcommand{\?}{} % sometimes I need just a separator other than whitespace
\]
#+end_export
#+END:
