name: 'Build Site'

description: 'Build the Website as public.tar.gz'

runs:
  using: "composite"
  steps:
    # TODO
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
      with:
        install: true

    - name: Build Docker image and store in cache
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./docker
        push: false
        load: true
        tags: rs/emacs
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - run: ./bin/run-build-in-docker.sh
      shell: bash

    # Install non-GUI emacs:
    - run: sudo apt install emacs-nox --yes
      shell: bash
    - run: make
      shell: bash
    - run: tar -czf public.tar.gz public
      shell: bash
