name: 'Build Site'

description: 'Build the Website as public.tar.gz'

runs:
  using: "composite"
  steps:
    # Install non-GUI emacs:
    - run: sudo apt install emacs-nox --yes
      shell: bash
    - run: make
      shell: bash
    - run: tar -czf public.tar.gz public
      shell: bash
