name: 'Build Site'

description: 'Build the Website as public.tar.gz'

runs:
  using: "composite"
  steps:
    - run: ./bin/run-build-in-docker.sh
      shell: bash
    - run: tar -czf public.tar.gz public
      shell: bash
