name: 'Full build job'

description: 'Checkout repo, build all, and upload artifacts'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker Buildx
      uses: ./.github/actions/docker-buildx
    - run: ./bin/run-build-in-docker.sh
      shell: bash
    - run: ./bin/run-tests-in-docker.sh
      shell: bash
    - name: Upload artifacts
      uses: ./.github/actions/upload-artifacts
