#+title:  Appendix 2 - Group Theory
#+author: Reinhard Stahn
#+setupfile: ./inc/setupfile.org
#+include: ./inc/latex-macros.org
#+property: header-args:python :session *appendix-2* :tangle appendix_2.py

#+toc: headlines 2
* Setup
- TODOs ::
  - more complete version of Schur's lemma
  - Present the minimal polynomial (FIXME: it is not the /minimal/ polynomial) property
    conclude that character values are sums of $d$ =r=-th roots of unity.
  - What about character tables?
  - Move the regular representation stuff from A2.17 here.
  - Define the scalar product (and refer to Thm A2.4, A2.5)

* Exercises
** Exercise A2.11 (Characters)
Prove the following properties of characters on a /finite/ (and complex) matrix group:

1. $\chi(I)=n$,
2. $\abs{\chi(g)}\leq n$,
3. $\abs{\chi(g)} = n \Rightarrow g = e^{i\theta} I$,
4. Characters are constant on conjugacy classes,
5. $\chi(g^{-1}) = \chi(g)^*$ (complex conjugate),
6. $\chi(g)$ is an algebraic number.

*** Proof of (1)
This should be clear since the identity matrix has exactly $n$ ones on the diagonal.

*** Proof of (2)
Recall that the trace is just the sum of all eigenvalues, counted with multiplicity
(exactly $n$ numbers). Let $\lambda$ be one of the eigenvalues and consider a
corresponding eigenvector $v$. Then

$$
  g^a \ket{v} = \lambda^a \ket{v} .
$$

Each element of a finite group has finite order. Hence there is an integer $r$ such that
$g^r=e$ and thus

<<root-of-unity-property>>
$$ \lambda^r=1 $$

holds for any eigenvalue. In particular $|\lambda|=1$. Hence, by the triangle inequality
we get the claim. QED.

*Remark:* The equation [[root-of-unity-property][above]] is a very interesting property. It shows that the [[https://en.wikipedia.org/wiki/Minimal_polynomial_(linear_algebra)][minimal
polynomial]] of an element of a /finite/ matrix group has a very special form. QED.

*** Proof of (3)
This follows from the [[root-of-unity-property][special form]] of the minimal polynomial too, together with the fact
that the triangle inequality is strict iff all summands are colinear.

*** Proof of (4)
We have to show $\chi(h^{-1}gh)=\chi(g)$. This follows from the cyclicity property of the trace:

$$
  \trace{ab} = \sum_{ij} a_{ij} b_{ji} = \sum_{ji} b_{ji} a_{ij} = \trace{ba} .
$$

QED.

*** Proof of (5)
Since we work on vector spaces of /complex/ numbers, the [[https://en.wikipedia.org/wiki/Characteristic_polynomial][characteristic polynomial]] (not
minimal polynomial this time) can be factored into /linear/ polynomials:

$$
  \prod_{i=1}^n (\lambda_i - g) .
$$

This assumes that the eigenvalues (including multiplicities are $\lambda_i$). Multiplying
this by $g^{-n}$ shows that the eigenvalues of $g^{-1}$ are $\lambda_i^{-1}$ (including
multiplicities). Again from the [[root-of-unity-property][minimal polynomial]] we get $\lambda_i^{-1}=\lambda_i^*$
which implies the claim. QED.

*** Proof of (6)
Again by the minimal polynomial the character is just a sum of roots of unity. The latter
are algebraic. According to [[https://en.wikipedia.org/wiki/Algebraic_number#Field][wikipedia]] algebraic numbers form a field (in fact, they are the
algebraic closure of the rational numbers). Hence sums of algebraic numbers are algebraic
too. QED.

** Exercise A2.12 (Unitary matrix groups)
A unitary matrix group is comprised solely of unitary matrices. Show that every finite
matrix group is equivalent to a unitary matrix group. If a representation of a group
consists entirely of unitary matrices, we may refer to it as being a /unitary
representation/.

- Remark ::
  - The solution of exercise A2.11 already shows that finite matrix groups are comprised
    of "very special" matrices which are "almost" unitary (in a sense). So it is nice to
    see an example of a non-unitary matrix group (see below).

*** Example for the remark
An example of a non-unitary matrix group is generated by

$$
  g = \begin{bmatrix} 1 & a \\ 0 & -1 \end{bmatrix} .
$$

Clearly $\langle g \rangle = \{I, g\}$, since $g^2=I$. Moreover $g$ is not unitary for any
$a\neq0$. On the other hand $g$ is diagonalizable (its eigenvalues are $\pm1$).

On the other hand for $a\neq0$ the following is a generator for a representation of $\ZZ$
which is /not/ diagonalizable (up to a factor the matrix is already in [[https://en.wikipedia.org/wiki/Jordan_normal_form][Jordan normal
form]]):

$$
  g = \begin{bmatrix} 1 & a \\ 0 & 1 \end{bmatrix} .
$$

Hence a conjugation $g\mapsto hgh\inv$ (as in the proof below) won't make this into a
unitary group.

*** Proof
Let us define the positive semi-definite operator

$$
  p = \sum_{h\in G} h^\dagger h .
$$

This operator is invertible since $\bra{u}p\ket{u} > 0$ for any non-zero vector $u$. By
the functional calculus for hermitian matrices we can uniquely define a positive
semi-definite operator $\sqrt{p}$ whose square is $p$ (if $p$ is already diagonal just
take the square roots of each entry and else apply the spectral theorem first to make it
diagonal). The matrix $\sqrt{p}$ is invertible too.

Now define the mapping $\phi$ as the conjugation with $\sqrt{p}$:

$$
  \phi: g \mapsto \sqrt{p} g \sqrt{p}^{-1}.
$$

It is easy to see that this is an isomorphism of $G$ to some other matrix group
$G'$. Moreover this matrix group is unitary since every $g\in G$ acts as a permutation on
$G$ which implies:

$$
  \phi(g)^\dagger \phi(g) = \sqrt{p}^{-1} g^\dagger p g \sqrt{p}^{-1}
  = \sqrt{p}^{-1} \sum_{h\in G} (hg)^\dagger hg \sqrt{p}^{-1}
  = \sqrt{p}^{-1} p \sqrt{p}^{-1} = I .
$$

Since conjugation preserves the trace (exercise A2.11) we are done. QED.

** Exercise A2.13
Show that every irreducible Abelian matrix group is one dimensional.

*** Proof
First observe an addition to Schur's Lemma. If (in the notation of the book) $G=H$ and
$h_i=g_i$ one can actually show that necessarily $S=\alpha I$ for some $\alpha\in\CC$. Let
us prove this briefly. $S$ must have an eigenvalue $\alpha$. Clearly
$g_i(S-\alpha)=(S-\alpha)h_i$. Since $S-\alpha$ is singular it must be zero by Schur's
Lemma - concluding the proof of the addition to Schur's lemma.

Let $s$ by an /arbitrary/ element of the abelian group. Since the group is abelian we have:

$$
  g s = s g
$$

for any element $g$. By Schur's Lemma we have $s=\alpha_s I$ for some complex number
$\alpha_s$. Since $s$ was arbitrary we have that any element is of this form. A group of
multiples of the identity can clearly only be irreducible if it is one dimensional. QED.

** TODO Exercise A2.14
Prove that if $\rho$ is an irreducible representation of $G$, then $|G|/d_\rho$ is an
integer.

** TODO Exercise A2.15
Using the Fundamental Theorem, prove that characters are orthogonal, that is:

$$
  \sum_{i=1}^r r_i (\chi_i^p)^* \chi_i^q = \abs{G} \delta_{pq} \quad \text{and} \quad
  \sum_{p=1}^r (\chi_i^p)^* \chi_j^p = \frac{\abs{G}}{r_i} \delta_{ij} ,
$$

where $p$, $q$, and $\delta_{pq}$ have the same meaning as in the theorem, and $\chi_i^p$
is the value the character of the $p$​th irreducible representation takes on the $i$​th
conjugacy class of $G$, and $r_i$ is the size of the $i$​th conjugacy class.

** TODO Exercise A2.16
$S_3$ is the group of permutations of three elements. Suppose we order these as mapping
=123= to: =123=; =231=; =312=; =213=; =132=, and =321=, respectively. Show that

there exist two one-dimensional irreducible representations of $S_3$, one of which is
trivial, and the other of which is =1=, =1=, =1=, =-1=, =−1=, =−1=, corresponding in order
to the six permutations given earlier. Also show that there exists a two-dimensional
irreducible representation, with the matrices

: TODO matrices here

Verify that the representations are orthogonal.

*** Solution

# TODO
#+begin_src python
  arep = [
      Matrix([[1, 0], [0, 1]]),
      Matrix([[-1, -sqrt(3)], [sqrt(3), -1]]) / 2,
      Matrix([[-1, sqrt(3)], [-sqrt(3), -1]]) / 2,
      Matrix([[-1, 0], [0, 1]]),
      Matrix([[1, sqrt(3)], [sqrt(3), -1]]) / 2,
      Matrix([[1, -sqrt(3)], [-sqrt(3), -1]]) / 2
  ]
#+end_src

** Exercise A2.17
Prove that the regular representation is faithful.

*** Proof
This is more or less obvious. In fact, the regular representation $\rho^R$ can be
/identified/ with the vector space $R=\CC^{\oplus G}$ made up of the following formal sums:

$$
  v = \sum_{h \in G} \lambda_h h ,
$$

where $\lambda_h\in\CC$ and $G$ is considered as a basis (so that the $\lambda_h$ are
unique). See also the entry for [[https://en.wikipedia.org/wiki/Free_module][free module]] on wikipedia.  With this definition $\rho^R$
is given by

$$
  \rho^R(g) v = \sum_{h \in G} \lambda_h (gh) .
$$

Clearly this is a homomorphism of groups. It is also an isomorphism since
$\rho^R(g)=\rho^R(e)$ implies $\rho^R(g)e=\rho^R(e)e$ which in turn implies $ge=e$, hence
$g=e$. QED.

** Exercise A2.18
Show that the character of the regular representation is zero except on the representation
of the identity element, for which $\chi^R(I)=\abs{G}$.

*** Proof
We have

$$
  \rho^R(g)_{ij} = \begin{cases} 1 & \text{if } g g_i=g_j \\ 0 & \text{else.} \end{cases}
$$

$g g_i=g_i$ is equivalent to $g=e$. Hence $\rho^R(g)$ has /any/ non-zero entries on
the diagonal iff $g=e$. QED.

** Exercise A2.19
Use Theorem A2.5 to show that the regular representation contains $d_{\rho^p}$ instances
of each irreducible representation $\rho^p$. Thus, if $R$ denotes the regular
representation, and $\hat{G}$ denotes the set of all inequivalent irreducible
representations, then

$$
  \chi_i^R = \sum_{\rho \in \hat{G}} d_\rho \chi_i^\rho .
$$

*** Proof
By Theorem A2.4 (the fundamental theorem) the irreducible representations are an
orthonormal basis of the set of class functions. Hence

$$
  \chi^R = \sum_{\rho\in\hat{G}} c_\rho \chi^\rho
$$

for /some/ $c_\rho\in\CC$. Let us calclute the value of the coefficients:

$$
  c_\rho = \langle \chi^\rho, \chi^R \rangle = \abs{G}\inv \chi^\rho(e)^* \chi^R(e) = d_\rho .
$$

The second equality follows from exercise A2.18 and the third one from exercise
A2.11(1). QED.

** Exercise A2.20
The character of the regular representation is zero except for the conjugacy class
containing $e$ (which is $\{e\}$), the identity element in $G$ (see exercise A2.18). Show,
therefore, that

$$
  \sum_{\rho \in \hat{G}} d_\rho \chi^\rho(g) = \abs{G} \delta_{ge} .
$$

*** Proof
We have

$$
  \sum_{\rho \in \hat{G}} d_\rho \chi^\rho(g)
  = \chi^R(g) = \abs{G} \delta_{ge} .
$$

The first equality follows from exercise A2.19. The second one from exercise A2.18. QED.

** Exercise A2.21
Show that $\sum_{\rho\in\hat{G}}d_\rho^2=\abs{G}$.

*** Proof
We have

$$
  \sum_{\rho\in\hat{G}} d_\rho^2 = \sum_{\rho\in\hat{G}} d_\rho \chi^\rho(e) = \chi^R(e) = \abs{G} .
$$

The first equality follows from exercise A2.11(1), the second from A2.19 and the third
again from A2.11(1). QED.
