#+title:  Chapter 10
#+author: Reinhard Stahn
#+setupfile: ./inc/setupfile.org
#+include: ./inc/latex-macros.org
#+property: header-args:sage :session *sage-chapter-10* :tangle chapter_10.sage
# python session just for qiskit since sage integers dont work well with qiskit:
#+property: header-args:python :session *python-chapter-10* :tangle no

#+toc: headlines 2

* Setup
# Hidden imports
#+name: imports-chapter-7-2
#+begin_src python :exports none
  from qiskit.circuit import QuantumCircuit, QuantumRegister, Parameter as Param
#+end_src

* Exercises
** Exercise 10.1
Verify that the encoding circuit in Figure 10.2 works as claimed.

#+RESULTS[b2469d3d1659de6df9ffe41f5443d686897376b9]: exercise-10.1-circuit
:
: |psi>: ──■────■──
:        ┌─┴─┐  │
: |0>_0: ┤ X ├──┼──
:        └───┘┌─┴─┐
: |0>_1: ─────┤ X ├
:             └───┘


#+name: exercise-10.1-circuit
#+begin_src python :results replace :cache yes :exports results
  qr0 = QuantumRegister(1, "|psi>")
  qr1 = QuantumRegister(2, "|0>")

  qc = QuantumCircuit(qr0, qr1)
  qc.cx(0, 1)
  qc.cx(0, 2)

  qc.draw()
#+end_src

*** Solution
This is really just observing that the circuit acts like this on the /relevant/ basis
states

\begin{align*}
  \ket{000} &\mapsto \ket{000} , \\
  \ket{100} &\mapsto \ket{111} . \\
\end{align*}

The rest follows by linearity.

** Exercise 10.2
The action of the bit flip channel can be described by the quantum operation
$\calE(\rho)=(1-p)\rho+pX\rho\?X$. Show that this may be given an alternate operator-sum
representation, as $\calE(\rho)=(1-2p)\rho+2pP_+\rho\?P_++2pP_-\rho\?P_-$ where $P_+$ and
$P_-$ are projectors onto the $+1$ and $-1$ eigenstates of $X$,
$(\ket{0}+\ket{1})/\sqrt{2}$ and $(\ket{0}+\ket{1})/\sqrt{2}$ respectively.  This latter
representation can be understood as a model in which the qubit is left alone with
probability $1-2p$, and is ‘measured’ by the environment in the $\ket{+}$, $\ket{-}$ basis
with probability $2p$.

*** Proof
Note that $X=P_+-P_-$ and $I=P_++P_-$. Hence

$$
  X\rho X = P_+\rho P_+ + P_-\rho P_- - (P_+\rho P_- + P_-\rho P_+)
  = 2(P_+\rho P_+ + P_-\rho P_-) - I\rho I .
$$

Hence

$$
  \calE(\rho) = (1 - 2p)\rho + 2p (P_+\rho P_+ + P_-\rho P_-) .
$$

QED.

** Exercise 10.3
Show by explicit calculation that measuring $Z_1Z_2$ followed by $Z_2Z_3$ is equivalent,
up to labeling of the measurement outcomes, to measuring the four projectors defined by
(10.5)–(10.8), in the sense that both procedures result in the same measurement statistics
and post-measurement states.

*** Proof
Let us define the following projectors

\begin{align*}
  P_{ijk} &= \proj{i}\otimes\proj{j}\otimes\proj{k} , \\
  P_{ijx} &= \proj{i}\otimes\proj{j}\otimes I , \\
  P_{xij} &= I\otimes \proj{i}\otimes\proj{j} .
\end{align*}

That is, the $x$ has a special meaning and just stands for the place where the identity
acts. Define $P_{ixx}$ etc analogously. Note that e.g. $P_{ixx}P_{xjx}=P_{ijx}$. Since
$Z_1=P_{0xx}-P_{1xx}$, $Z_2=P_{x0x}-P_{x1x}$, $Z_3=P_{xx0}-P_{xx1}$ we have the following
spectral decomposition of the observables we are interested in:

\begin{align*}
  Z_1Z_2 &= P_{00x} + P_{11x} - P_{01x} - P_{10x} , \\
  Z_2Z_3 &= P_{x00} + P_{x11} - P_{x01} - P_{x10} .
\end{align*}

Let $P_j$ for $j=0..3$ be the projectors from (10.5) to (10.8). If we measure for example
$+1$ for $Z_1Z_2$ and $+1$ for $Z_2Z_3$ this corresponds to the projection (note: the
order of the projections is not important due to commutativity)

$$
  (+1, +1):\; (P_{00x} + P_{11x})(P_{x00} + P_{x11}) = P_{000} + P_{111} = P_0 .
$$

In the same way the other three measurements can be mapped to the $P_j$ too:

\begin{align*}
  &(+1, -1):\; (P_{00x} + P_{11x})(P_{x01} + P_{x10}) = P_{001} + P_{110} = P_3 , \\
  &(-1, +1):\; (P_{01x} + P_{10x})(P_{x00} + P_{x11}) = P_{100} + P_{011} = P_1 , \\
  &(-1, -1):\; (P_{01x} + P_{10x})(P_{x01} + P_{x10}) = P_{101} + P_{010} = P_2 .
\end{align*}

Hence the projectors are the same, just re-labeled. QED.

** Exercise 10.4
Consider the three qubit bit flip code. Suppose we had performed the error syndrome
measurement by measuring the eight orthogonal projectors corresponding to projections onto
the eight computational basis states.

1. Write out the projectors corresponding to this measurement, and explain how the
   measurement result can be used to diagnose the error syndrome: either no bits flipped or
   bit number $j$ flipped, where $j$ is in the range one to three.
2. Show that the recovery procedure works only for computational basis states.
3. What is the minimum fidelity for the error-correction procedure?

*** Solution for part 1
The projectors are just $P_j=\proj{j}$ for $j=0..7$ (note that the binary representations
for the numbers from $0$ to $7$ are $000$, $001$, $010$, $011$, $100$, $101$, $110$,
$111$). A corresponding observable distinguishing each projector would be
$A=\sum_jj\proj{j}$.

Recall that the encoded state is $\ket{\psi}=a\ket{000}+b\ket{111}$. Let $k=0$, $k=1$,
$k=2$, $k=3$ denote /no error/, /error in qubit 1, 2, 3/, respectively. Let $M_k$ be the
set of possible measurements for the given value of $k$. We have

<<exercise-10.4-1>>
\begin{align*}
  M_0 &= \{0, 7\} , \\
  M_1 &= \{1, 6\} , \\
  M_2 &= \{2, 5\} , \\
  M_3 &= \{4, 3\} .
\end{align*}

Moreover, measuring $0,1,2,4$ happens with probability $\abs{a}^2$ and measuring $7,6,5,3$
happens with probability $\abs{b}^2$ (conditioned on a fixed value for $j$). Since the
four sets are disjoint we can infer the error (the value of $k$) from the measurement
(e.g. measuring $1$ or $6$ implies that the error was $k=1$ (with certainty if only one of
the three errors "is allowed" to happen)).

*** Solution for part 2
If we measure $j$ and infer the error $k$ [[exercise-10.4-1][according to the sets]] $M_k$ we would correct it
by applying $X_k$ to the state. In other words, the following quantum operation $\calR$
performs the syndrome measurement followed by the recovery:

\begin{align*}
  E_0 &= P_0, \\ E_1 &= X_1P_1, \\ E_2 &= X_2P_2, \\ E_3 &= X_3P_3, \\
  E_4 &= X_3P_4, \\ E_5 &= X_2P_5, \\ E_6 &= X_1P_6, \\ E_7 &= P_7 .
\end{align*}

Note that $\calR$ is indeed trace-preserving ($\sum_jE_j^\dagger\?E_j)=I$). Recall
$\ket{\psi}=a\ket{000}+b\ket{111}$. Then (the /no error/ case)

$$
  \calR(\ket{\psi}) = \abs{a}^2 \proj{000} + \abs{b}^2 \proj{111} .
$$

The same formula holds for $\ket{\psi}$ replaced by $X_k\ket{\psi}$ ($k=1..3$). Hence, for
the following noise channel

$$
  \calE(\rho) = (1-p)\rho + \sum_{k=1}^3 p_k X_k \rho X_k
$$

where $\sum_kp_k=p$ (this implies trace-preservation, but we could more generally assume
$\ldots\leq\?p$, meaning that with certain probability "something else" happens), which
stands for having at most one bit-flip (with probability $p_k$ at position $k$), we have

$$
  \calR\circ\calE(\ket{\psi}) = \abs{a}^2 \proj{000} + \abs{b}^2 \proj{111} .
$$

(If $\calE$ was not trace-preserving the RHS would have a factor $1-p+\sum_jp_j$.) Hence
the bit-flip error gets indeed corrected, but unwanted side effects happen too. The final
state after recovery is either $\ket{000}$ (probability $\abs{a}^2$) or $\ket{111}$
(probability $\abs{b}^2$). That is the state collapses to a basis state. This is only
correct if $\ket{\psi}$ was already in a basis state ($a=0$ or $b=0$) - which is the claim
of part 2.

*** Solution for part 3
Let us consider two cases:

1. We do not get to know the results of the syndrome measurement.
2. We get to know the results of the syndrome measurement.

In case 1 the whole error correction procedure is given by $\calR$ from the solution of
part 2. Let $\rho=\calR\circ\calE(\ket{\psi})$. Then

$$
  F(\ket{\psi},\rho) = \sqrt{\bra{\psi}\rho\ket{\psi}} = \sqrt{\abs{a}^4 + \abs{b}^4} .
$$

Since $\abs{a}^2+\abs{b}^2=1$ the minimum occurs at $\abs{a}^2=\abs{b}^2=1/2$. Hence
$F\geq1/\sqrt{2}$ in that case.

In case 2 the post-correction state $\rho$ is either $\ket{000}$ (probability $\abs{a}^2$)
or $\ket{111}$ (probability $\abs{b}^2$). Hence

$$
  F(\ket{\psi},\rho) \in \left\{\sqrt{\braket{\psi}{i_L}\braket{i_L}{\psi}} \; \middle| \; i\in\{0,1\}\right\}
  = \{\abs{a}, \abs{b}\} ,
$$

where the first alternative occurs with probability $\abs{a}^2$ and the second one with
$\abs{b}^2$.

In both cases the minimial fidelity does not depend on the specifics of the noise model
and in particular is always bad if $\abs{a}$ and $\abs{b}$ are bounded away from $0$ (or
equivalently, from $1$).

- Remark :: The minimum fidelity of case 1 is the weighted root square mean of the two
  possible fidelities of case 2. The weights are $\abs{a}^2$ and $\abs{b}^2$. See e.g.
  [[https://en.wikipedia.org/wiki/Generalized_mean][generalized mean]] on wikipedia for more infos. To make this more apparent consider
  $\sigma=p\proj{0}+(1-p)\proj{1}$ (and $\ket{\psi}=a\ket{0}+b\ket{1}$):

  $$
  F(\ket{\psi},\sigma) = \sqrt{\bra{\psi}\sigma\ket{\psi}} = \sqrt{p\abs{a}^2+(1-p)\abs{b}^2} .
  $$

  Here $p$ and $1-p$ are the weights.

** Exercise 10.5
Show that the syndrome measurement for detecting phase flip errors in the Shor code
corresponds to measuring the observables $A=X_1X_2X_3X_4X_5X_6$ and
$B=X_4X_5X_6X_7X_8X_9$.

*** Proof
:PROPERTIES:
:CUSTOM_ID: exercise-10.5-solution
:END:
Let us denote

\begin{align*}
  \ket{\pi} &= \frac{1}{\sqrt{2}} (\ket{000} + \ket{111}) , \\
  \ket{\mu} &= \frac{1}{\sqrt{2}} (\ket{000} - \ket{111}) .
\end{align*}

With this notation the Shor code is given by

\begin{align*}
  \ket{0_L} &= \ket{\pi\pi\pi} , \\
  \ket{1_L} &= \ket{\mu\mu\mu} , \\
\end{align*}

Hence we have the following encoding:

$$
  \ket{\psi} = \ket{\psi_0} = a\ket{0_L} + b\ket{1_L} = a\ket{\pi\pi\pi} + b\ket{\mu\mu\mu} .
$$

In this notation a phase flip error is represented naturally. For example a phase flip in
one of the three qubits in the first block of $\ket{\psi}$ is given by

$$
  \ket{\psi_1} = a\ket{\mu\pi\pi} + b\ket{\pi\mu\mu} .
$$

It doesn't matter in which of the three qubits, it always leads to the same state. The
other two errors (phase flip in the second or third block) are given by

\begin{align*}
  \ket{\psi_2} &= a\ket{\pi\mu\pi} + b\ket{\mu\pi\mu} , \\
  \ket{\psi_3} &= a\ket{\pi\pi\mu} + b\ket{\mu\mu\pi} .
\end{align*}

Now observe that

\begin{align*}
  X_1X_2X_3 \ket{\pi} &= + \ket{\pi} , \\
  X_1X_2X_3 \ket{\mu} &= - \ket{\mu} .
\end{align*}

Hence e.g. measuring a state $\ket{ijk}$ ($i,j,k\in\{\pi,\mu\}$) with respect to $A$
detects if $i=j$ (measurement result: $+1$) or $i\neq\?j$ (measurement result:
$+1$). Because of their special structure this translates to $\ket{\psi_k}$. For the four
errors (first one is /no error/) we get the following measurement results (each with
certainty):

| $k$ ($\ket{\psi_k}$) | $A$ | $B$ |
|----------------------+-----+-----|
|                    0 |  +1 |  +1 |
|                    1 |  -1 |  +1 |
|                    2 |  -1 |  -1 |
|                    3 |  +1 |  -1 |

Hence we can infer the syndrome $k$ (which error occured) from the measurement - as
desired. QED.

** Exercise 10.6
Show that recovery from a phase flip on any of the first three qubits may be accomplished
by applying the operator $Z_1Z_2Z_3$.

*** Proof
Let us reuse the notation from the [[#exercise-10.5-solution][solution]] of exercise 10.5. Clearly

$$
  Z_1Z_2Z_3 \ket{\pi} = \ket{\mu} \text{ and } Z_1Z_2Z_3 \ket{\mu} = \ket{\pi} .
$$

An error in the first three qubits means that the corresponding state is
$\ket{\psi_1}$. By the above we have:

$$
  Z_1Z_2Z_3 \ket{\psi_1} = \ket{\psi} .
$$

QED.
