#+title:  Solutions for the bible of Quantum Computation and Quantum Information
#+author: Reinhard Stahn
#+setupfile: ./inc/setupfile.org

# Intro text for the generated HTML site:
# TODO: once the deployment uses org v9.5 or higher use org-cite in the paragraph below: [cite: @ChuangNielsen2011]
This website contains solutions for /some/ of the exercises from `Quantum Computation and Quantum
Information` (Nielsen, Michael A. and Chuang, Isaac L., 2011) (aka "Mike and Ike"). I am not an
expert in quantum mechanics but I am an experienced mathematician and a software developer who
enjoys solving these exercises. There are already tons of solutions out there but some solutions are
hard to find and so I think there is a certain value in sharing my solutions.

The site is generated from [[https://orgmode.org/index.html][org-mode]] files hosted on [[https://github.com/rainij/solutions-qcqi-nielsen-chuang][github]]. The code within the org files is mostly
python. To interact with it you can /tangle/ the org file into a python file which then can be
loaded into =ipython=. But you probably need [[https://www.gnu.org/software/emacs/][Emacs]] to do so, because only Emacs has support for the
more sophisticated features of the almighty org-mode. See the [[https://github.com/rainij/solutions-qcqi-nielsen-chuang][README]] of the repository for more
information.

- [[file:notation.org][Notation]]
- [[file:utils.org][Utilities]]
- Part I
  - [[file:chapter_2.org][Chapter 2]]
  - [[file:chapter_3.org][Chapter 3]]
- Part II
  - [[file:chapter_4.org][Chapter 4]]
  - [[file:chapter_5.org][Chapter 5]]
