#+title:  Solutions for the bible of Quantum Computation and Quantum Information
#+author: Reinhard Stahn
#+setupfile: ./inc/setupfile.org

# Intro text for the generated HTML site:
This website contains solutions for /some/ of the exercises from `Quantum Computation and
Quantum Information` [cite: @ChuangNielsen2011] (aka "Mike and Ike"). I am not an expert
in quantum mechanics but I am an experienced mathematician and a software developer who
enjoys solving these exercises. There are already tons of solutions out there but some
solutions are hard to find and so I think there is a certain value in sharing my
solutions.

The site is generated from [[https://orgmode.org/index.html][org-mode]] files hosted on [[https://github.com/rainij/solutions-qcqi-nielsen-chuang][github]]. The code within the org files
is mostly python. To interact with it you can /tangle/ the org file into a python file
which then can be loaded into =ipython= (or =jupyter=). For your convenience I prepared
[[./tangled.tar.gz][the tangled sources]] for download.

- [[file:notation.org][Notation]]
- [[file:utils.org][Utilities]]
- [[file:links.org][Links]]
- Part I
  - [[file:chapter_2.org][Chapter 2]]
  - [[file:chapter_3.org][Chapter 3]]
- Part II
  - [[file:chapter_4.org][Chapter 4]]
  - [[file:chapter_5.org][Chapter 5]]
  - [[file:chapter_6.org][Chapter 6]]
  - [[file:chapter_7.org][Chapter 7]]
- Part III
  - [[file:chapter_8.org][Chapter 8]]
  - [[file:chapter_9.org][Chapter 9]]
  - [[file:chapter_10.org][Chapter 10]]
- Appendices
  - [[file:appendix_2.org][Appendix 2]]
- More
  - [[file:continued_fractions.org][On Continued Fractions]]

#+print_bibliography:
