#+title:  Solutions for the bible of Quantum Computation and Quantum Information
#+author: Reinhard Stahn
#+setupfile: ./inc/setupfile.org

This website contains solutions for most of the exercises from `Quantum Computation and
Quantum Information` [cite: @ChuangNielsen2011] (aka "Mike and Ike"). I built it in 2023
to prepare for a job in quantum computation (which I got in 2024). At that time I worked
as a software developer. I had no prior experience in quantum computation but I was
already an expierenced mathematician (PhD in 2017).

I do not actively update the site but I leave it online in the hope that it is helpful for
others learning the subject.

The site is generated from [[https://orgmode.org/index.html][org-mode]] files hosted on [[https://github.com/rainij/solutions-qcqi-nielsen-chuang][github]]. It contains code blocks
written in python or sage ([[https://www.sagemath.org/][/sage/]] is a python based computer algebra system). Do not
expect those to work anymore (e.g. some rely on old versions of qiskit prior
v1.0). Nevertheless they might still be informative enough to aid understanding the
solutions.

- [[file:notation.org][Notation]]
- [[file:utils.org][Utilities]]
- [[file:links.org][Links]]
- Part I
  - [[file:chapter_2.org][Chapter 2]]
  - [[file:chapter_3.org][Chapter 3]]
- Part II
  - [[file:chapter_4.org][Chapter 4]]
  - [[file:chapter_5.org][Chapter 5]]
  - [[file:chapter_6.org][Chapter 6]]
  - [[file:chapter_7.org][Chapter 7]]
- Part III
  - [[file:chapter_8.org][Chapter 8]]
  - [[file:chapter_9.org][Chapter 9]]
  - [[file:chapter_10.org][Chapter 10]]
- Appendices
  - [[file:appendix_2.org][Appendix 2]]
- More
  - [[file:continued_fractions.org][On Continued Fractions]]

#+print_bibliography:
