#+title:  Links
#+author: Reinhard Stahn
#+setupfile: ./inc/setupfile.org

* Other Collections of Solutions
There are /alot/ of solutions out there (mostly as pdf on Github or as answers on
StackExchange). I do not try to list them all but only the most interesting ones (based on
my personal opinion).

A word of warning: Take any solutions with a grain of salt (applies to my site
too). Sometimes, after I solved a /challenging/ exercise I try to google it to find out
how others approach the problem. For each of these exercises the percentage of /just
wrong/ solutions was very high. Sometimes I couldn't find any correct solution. Even
worse, some solutions gave the impression that the exercise is no big deal and the
solution is straightforward (which might be true but at least their solution did not
justify this).

- [[https://quantumcomputing.stackexchange.com/questions/tagged/nielsen-and-chuang][stackexchange]]: You probably already knew this, just in case ...
- [[https://github.com/jacobwatkins1/Nielsen-and-Chuang-Solutions][jacobwatkins1]]: Good quality, every chapter is touched, some are complete.

* Misc

- [[https://www.michaelnielsen.org/qcqi/errata/errata/errata.html][Errata]]: Seems to be not updated anymore and misses /a lot/ of errors which are still in
  the book. Yes, the book is great but I think it contains more errors than the typical
  (good) math book (and yes it is a /math/ book 😉).
- [[https://quantum.country/][quantum country]]: So far I had no time to look into it but the website looks awesome.
