name: Build Website, upload artifact

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Buildx
        uses: ./.github/actions/docker-buildx
      - name: Build Website and upload Artifact
        uses: ./.github/actions/build-site-and-upload-artifacts
